# Import Section

In [1]:
import os
import json
import pandas as pd
import psycopg2
import plotly_express as px

# Aggregated_Insurance

In [2]:
#aggregated Insurance
path1 = "C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/insurance/country/india/state/"
aggre_ins_list = os.listdir(path1)
columns1={"States":[], "Years":[], "Quarter":[], "Transaction_Type":[], "Transaction_Count":[], "Transactions_amount":[]}

for state in aggre_ins_list:
    current_states = path1 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            A=json.load(data)
            for i in A["data"]["transactionData"]:
                name=i["name"]
                count=i["paymentInstruments"][0]["count"]
                amount=i["paymentInstruments"][0]["amount"]
                columns1["Transaction_Type"].append(name)
                columns1["Transaction_Count"].append(count)
                columns1["Transactions_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))

In [3]:
aggregated_insurance = pd.DataFrame(columns1)
aggregated_insurance

,States,Years,Quarter,Transaction_Type,Transaction_Count,Transactions_amount
0,andaman-&-nicobar-islands,2020,2,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,west-bengal,2023,4,Insurance,72712,100365562.0
678,west-bengal,2024,1,Insurance,79576,104987909.0
679,west-bengal,2024,2,Insurance,67048,89476633.0
680,west-bengal,2024,3,Insurance,77158,107451766.0
681,west-bengal,2024,4,Insurance,91719,120602777.0

In [4]:
aggregated_insurance["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [5]:
aggregated_insurance["States"]= aggregated_insurance["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggregated_insurance["States"]= aggregated_insurance["States"].str.replace("-", " ")
aggregated_insurance["States"]= aggregated_insurance["States"].str.title()

In [6]:
aggregated_insurance["States"]= aggregated_insurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [7]:
aggregated_insurance["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Aggregated_Transaction

In [8]:
#aggregated transaction - Detailed
path2 = "C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/"
aggre_trans_list = os.listdir(path2)
aggre_trans_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [9]:
for state in aggre_trans_list:
    current_state = path2 + state + "/"
    print(current_state)

C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/manipur/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/meghalaya/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/mizoram/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/nagaland/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/odisha/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/puducherry/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/punjab/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/rajasthan/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/sikkim/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/tamil-nadu/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/telangana/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/tripura/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/uttar-pradesh/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/uttarakhand/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/west-bengal/

In [10]:
for state in aggre_trans_list:
    current_states = path2 + state + "/"
    aggre_year_list=os.listdir(current_states)
    print(aggre_year_list)

['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']
['2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [11]:
for state in aggre_trans_list:
    current_states = path2 + state + "/"
    aggre_year_list=os.listdir(current_states)
    for year in aggre_year_list:
        current_year=current_states + year + "/"
        print(current_year)

C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andaman-&-nicobar-islands/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/andhra-pradesh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/arunachal-pradesh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/assam/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/bihar/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chandigarh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/chhattisgarh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/dadra-&-nagar-haveli-&-daman-&-diu/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/delhi/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/goa/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/gujarat/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/haryana/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/himachal-pradesh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jammu-&-kashmir/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/jharkhand/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/karnataka/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/kerala/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/ladakh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/lakshadweep/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/madhya-pradesh/2024/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2018/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2019/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2020/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2021/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2022/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2023/
C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/transaction/country/india/state/maharashtra/2024/

In [12]:
columns2={"States":[], "Years":[], "Quarter":[], "Transaction_Type":[], "Transaction_Count":[], "Transactions_amount":[]}

for state in aggre_trans_list:
    current_states = path2 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            B=json.load(data)

In [13]:
B

{'success': True,
 'code': 'SUCCESS',
 'data': {'from': 1727740800000,
  'to': 1735344000000,
  'transactionData': [{'name': 'Merchant payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 655100809,
      'amount': 389286175909.0}]},
   {'name': 'Peer-to-peer payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 493217788,
      'amount': 1361927136312.0}]},
   {'name': 'Recharge & bill payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 76043195,
      'amount': 57534056540.0}]},
   {'name': 'Financial Services',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 2352084,
      'amount': 847296537.0}]},
   {'name': 'Others',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 421806,
      'amount': 505364108.0}]}]},
 'responseTimestamp': 1739974491270}

In [14]:
for i in B["data"]:
    print(i)

from
to
transactionData

In [15]:
 for i in B["data"]["transactionData"]:
    print(i)

{'name': 'Merchant payments', 'paymentInstruments': [{'type': 'TOTAL', 'count': 655100809, 'amount': 389286175909.0}]}
{'name': 'Peer-to-peer payments', 'paymentInstruments': [{'type': 'TOTAL', 'count': 493217788, 'amount': 1361927136312.0}]}
{'name': 'Recharge & bill payments', 'paymentInstruments': [{'type': 'TOTAL', 'count': 76043195, 'amount': 57534056540.0}]}
{'name': 'Financial Services', 'paymentInstruments': [{'type': 'TOTAL', 'count': 2352084, 'amount': 847296537.0}]}
{'name': 'Others', 'paymentInstruments': [{'type': 'TOTAL', 'count': 421806, 'amount': 505364108.0}]}

In [16]:
for i in B["data"]["transactionData"]:
    name=i["name"]
    print(name)

Merchant payments
Peer-to-peer payments
Recharge & bill payments
Financial Services
Others

In [17]:
B["data"]["transactionData"]

[{'name': 'Merchant payments',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 655100809,
    'amount': 389286175909.0}]},
 {'name': 'Peer-to-peer payments',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 493217788,
    'amount': 1361927136312.0}]},
 {'name': 'Recharge & bill payments',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 76043195,
    'amount': 57534056540.0}]},
 {'name': 'Financial Services',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 2352084,
    'amount': 847296537.0}]},
 {'name': 'Others',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 421806,
    'amount': 505364108.0}]}]

In [18]:
B["data"]["transactionData"][0]

{'name': 'Merchant payments',
 'paymentInstruments': [{'type': 'TOTAL',
   'count': 655100809,
   'amount': 389286175909.0}]}

In [19]:
B["data"]["transactionData"][0]["paymentInstruments"][0]

{'type': 'TOTAL', 'count': 655100809, 'amount': 389286175909.0}

In [20]:
B["data"]["transactionData"][0]["paymentInstruments"][0]["amount"]

389286175909.0

In [21]:
for i in B["data"]["transactionData"]:
    name=i["name"]
    count=i["paymentInstruments"][0]["count"]
    print(count)

655100809
493217788
76043195
2352084
421806

In [22]:
for i in B["data"]["transactionData"]:
    name=i["name"]
    count=i["paymentInstruments"][0]["count"]
    amount=i["paymentInstruments"][0]["amount"]
    columns2["Transaction_Type"].append(name)
    columns2["Transaction_Count"].append(count)
    columns2["Transactions_amount"].append(amount)
    columns2["States"].append(state)
    columns2["Years"].append(year)
    columns2["Quarter"].append(int(file.strip(".json")))

In [23]:
columns2={"States":[], "Years":[], "Quarter":[], "Transaction_Type":[], "Transaction_Count":[], "Transactions_amount":[]}

for state in aggre_trans_list:
    current_states = path2 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            #A=json.loads(data.read())
            B=json.load(data)
            for i in B["data"]["transactionData"]:
                name=i["name"]
                count=i["paymentInstruments"][0]["count"]
                amount=i["paymentInstruments"][0]["amount"]
                columns2["Transaction_Type"].append(name)
                columns2["Transaction_Count"].append(count)
                columns2["Transactions_amount"].append(amount)
                columns2["States"].append(state)
                columns2["Years"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

In [24]:
columns2

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'chhattisgarh',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  'dadra-&-nagar-haveli-&-daman-&-diu',
  ...],
 'Years': ['2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',

In [25]:
aggregated_transaction = pd.DataFrame(columns2)
aggregated_transaction

,States,Years,Quarter,Transaction_Type,Transaction_Count,Transactions_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [26]:
aggregated_transaction["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [27]:
aggregated_transaction["States"]= aggregated_transaction["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggregated_transaction["States"]= aggregated_transaction["States"].str.replace("-", " ")
aggregated_transaction["States"]= aggregated_transaction["States"].str.title()
aggregated_transaction["States"]= aggregated_transaction["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [28]:
aggregated_transaction["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Aggregated User

In [29]:
#aggregated_user
path3="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/user/country/india/state/"
aggre_user_list = os.listdir(path3)
columns3={"States":[], "Years":[], "Quarter":[], "Brands":[], "Transaction_Count":[], "Percentage":[]}

for state in aggre_user_list:
    current_states = path3 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            C=json.load(data)

In [30]:
print(C["data"])

{'aggregated': {'registeredUsers': 34750181, 'appOpens': 1994940763}, 'usersByDevice': None}

In [31]:
print(C["data"]["usersByDevice"])

None

In [32]:
try:
    for i in C["data"]["usersByDevice"]:
        brand=i["brand"]
        count=i["count"]
        percentage=i["percentage"]
        columns3["Brands"].append(brand)
        columns3["Transaction_Count"].append(count)
        columns3["Percentage"].append(percentage)
        columns3["States"].append(state)
        columns3["Years"].append(year)
        columns3["Quarter"].append(int(file.strip(".json")))
except:
    pass

In [33]:
#aggregated_user
path3="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/aggregated/user/country/india/state/"
aggre_user_list = os.listdir(path3)
columns3={"States":[], "Years":[], "Quarter":[], "Brands":[], "Transaction_Count":[], "Percentage":[]}

for state in aggre_user_list:
    current_states = path3 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            C=json.load(data)
            try:
                for i in C["data"]["usersByDevice"]:
                    brand=i["brand"]
                    count=i["count"]
                    percentage=i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_Count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))
            except:
                pass

In [34]:
columns3

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  ...],
 'Years': ['2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2018',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2019',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',

In [35]:
aggregated_user = pd.DataFrame(columns3)
aggregated_user

,States,Years,Quarter,Brands,Transaction_Count,Percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,0.049258
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,0.015056
6728,west-bengal,2022,1,Infinix,284678,0.012987
6729,west-bengal,2022,1,Asus,280347,0.012790
6730,west-bengal,2022,1,Apple,277752,0.012671
6731,west-bengal,2022,1,Others,2196334,0.100199

In [36]:
aggregated_user["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [37]:
aggregated_user["States"]= aggregated_user["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
aggregated_user["States"]= aggregated_user["States"].str.replace("-", " ")
aggregated_user["States"]= aggregated_user["States"].str.title()
aggregated_user["States"]= aggregated_user["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [38]:
aggregated_user["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Map Insurance

In [39]:
#Map_Insurance
path4="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/map/insurance/hover/country/india/state/"
map_ins_list = os.listdir(path4)
columns4={"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_Count":[], "Transaction_amount":[]}

for state in map_ins_list:
    current_states = path4 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            D=json.load(data)
            for i in D["data"]["hoverDataList"]:
                name=i["name"]
                count=i["metric"][0]["count"]
                amount=i["metric"][0]["amount"]
                columns4["Districts"].append(name)
                columns4["Transaction_Count"].append(count)
                columns4["Transaction_amount"].append(amount)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))

In [40]:
columns4

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  ...],
 'Years': ['2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2023',
  '2023',
  '2023',
  '2023',
  '2023',

In [41]:
map_insurance = pd.DataFrame(columns4)
map_insurance

,States,Years,Quarter,Districts,Transaction_Count,Transaction_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0

In [42]:
map_insurance["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [43]:
map_insurance["States"]= map_insurance["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
map_insurance["States"]= map_insurance["States"].str.replace("-", " ")
map_insurance["States"]= map_insurance["States"].str.title()
map_insurance["States"]= map_insurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [44]:
map_insurance["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Map Transaction

In [45]:
#Map_Transaction
path5="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/map/transaction/hover/country/india/state/"
map_transaction_list = os.listdir(path5)
columns5={"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_Count":[], "Transaction_amount":[]}

for state in map_transaction_list:
    current_states = path5 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            E=json.load(data)

In [46]:
E

{'success': True,
 'code': 'SUCCESS',
 'data': {'hoverDataList': [{'name': 'south twenty four parganas district',
    'metric': [{'type': 'TOTAL',
      'count': 76936211,
      'amount': 118552623594.0}]},
   {'name': 'purba bardhaman district',
    'metric': [{'type': 'TOTAL', 'count': 43690070, 'amount': 70602865584.0}]},
   {'name': 'uttar dinajpur district',
    'metric': [{'type': 'TOTAL', 'count': 37198721, 'amount': 61950132057.0}]},
   {'name': 'kalimpong district',
    'metric': [{'type': 'TOTAL', 'count': 1847818, 'amount': 2646924444.0}]},
   {'name': 'murshidabad district',
    'metric': [{'type': 'TOTAL',
      'count': 88522023,
      'amount': 156002264967.0}]},
   {'name': 'paschim medinipur district',
    'metric': [{'type': 'TOTAL', 'count': 58238212, 'amount': 84317739854.0}]},
   {'name': 'dakshin dinajpur district',
    'metric': [{'type': 'TOTAL', 'count': 13106067, 'amount': 21452200306.0}]},
   {'name': 'jalpaiguri district',
    'metric': [{'type': 'TOTAL', 'count': 20696406, 'amount': 27260366555.0}]},
   {'name': 'purulia district',
    'metric': [{'type': 'TOTAL', 'count': 24755604, 'amount': 26562481159.0}]},
   {'name': 'north twenty four parganas district',
    'metric': [{'type': 'TOTAL',
      'count': 199005333,
      'amount': 256651022725.0}]},
   {'name': 'bankura district',
    'metric': [{'type': 'TOTAL', 'count': 27187898, 'amount': 38703687103.0}]},
   {'name': 'jhargram district',
    'metric': [{'type': 'TOTAL', 'count': 8887423, 'amount': 11463658026.0}]},
   {'name': 'darjeeling district',
    'metric': [{'type': 'TOTAL', 'count': 27795067, 'amount': 40187454877.0}]},
   {'name': 'cooch behar district',
    'metric': [{'type': 'TOTAL', 'count': 33080526, 'amount': 42135373824.0}]},
   {'name': 'malda district',
    'metric': [{'type': 'TOTAL',
      'count': 63424613,
      'amount': 102421242316.0}]},
   {'name': 'howrah district',
    'metric': [{'type': 'TOTAL',
      'count': 67496284,
      'amount': 102576375745.0}]},
   {'name': 'hooghly district',
    'metric': [{'type': 'TOTAL', 'count': 59676576, 'amount': 90713828065.0}]},
   {'name': 'kolkata district',
    'metric': [{'type': 'TOTAL',
      'count': 133085069,
      'amount': 185223784274.0}]},
   {'name': 'alipurduar district',
    'metric': [{'type': 'TOTAL', 'count': 15875637, 'amount': 20992506730.0}]},
   {'name': 'paschim bardhaman district',
    'metric': [{'type': 'TOTAL', 'count': 56616799, 'amount': 69687350676.0}]},
   {'name': 'nadia district',
    'metric': [{'type': 'TOTAL',
      'count': 65274337,
      'amount': 107932013030.0}]},
   {'name': 'birbhum district',
    'metric': [{'type': 'TOTAL', 'count': 36905213, 'amount': 57787007226.0}]},
   {'name': 'purba medinipur district',
    'metric': [{'type': 'TOTAL',
      'count': 67833775,
      'amount': 114277126269.0}]}]},
 'responseTimestamp': 1739974491469}

In [47]:
E["data"]

{'hoverDataList': [{'name': 'south twenty four parganas district',
   'metric': [{'type': 'TOTAL', 'count': 76936211, 'amount': 118552623594.0}]},
  {'name': 'purba bardhaman district',
   'metric': [{'type': 'TOTAL', 'count': 43690070, 'amount': 70602865584.0}]},
  {'name': 'uttar dinajpur district',
   'metric': [{'type': 'TOTAL', 'count': 37198721, 'amount': 61950132057.0}]},
  {'name': 'kalimpong district',
   'metric': [{'type': 'TOTAL', 'count': 1847818, 'amount': 2646924444.0}]},
  {'name': 'murshidabad district',
   'metric': [{'type': 'TOTAL', 'count': 88522023, 'amount': 156002264967.0}]},
  {'name': 'paschim medinipur district',
   'metric': [{'type': 'TOTAL', 'count': 58238212, 'amount': 84317739854.0}]},
  {'name': 'dakshin dinajpur district',
   'metric': [{'type': 'TOTAL', 'count': 13106067, 'amount': 21452200306.0}]},
  {'name': 'jalpaiguri district',
   'metric': [{'type': 'TOTAL', 'count': 20696406, 'amount': 27260366555.0}]},
  {'name': 'purulia district',
   'metric': [{'type': 'TOTAL', 'count': 24755604, 'amount': 26562481159.0}]},
  {'name': 'north twenty four parganas district',
   'metric': [{'type': 'TOTAL',
     'count': 199005333,
     'amount': 256651022725.0}]},
  {'name': 'bankura district',
   'metric': [{'type': 'TOTAL', 'count': 27187898, 'amount': 38703687103.0}]},
  {'name': 'jhargram district',
   'metric': [{'type': 'TOTAL', 'count': 8887423, 'amount': 11463658026.0}]},
  {'name': 'darjeeling district',
   'metric': [{'type': 'TOTAL', 'count': 27795067, 'amount': 40187454877.0}]},
  {'name': 'cooch behar district',
   'metric': [{'type': 'TOTAL', 'count': 33080526, 'amount': 42135373824.0}]},
  {'name': 'malda district',
   'metric': [{'type': 'TOTAL', 'count': 63424613, 'amount': 102421242316.0}]},
  {'name': 'howrah district',
   'metric': [{'type': 'TOTAL', 'count': 67496284, 'amount': 102576375745.0}]},
  {'name': 'hooghly district',
   'metric': [{'type': 'TOTAL', 'count': 59676576, 'amount': 90713828065.0}]},
  {'name': 'kolkata district',
   'metric': [{'type': 'TOTAL',
     'count': 133085069,
     'amount': 185223784274.0}]},
  {'name': 'alipurduar district',
   'metric': [{'type': 'TOTAL', 'count': 15875637, 'amount': 20992506730.0}]},
  {'name': 'paschim bardhaman district',
   'metric': [{'type': 'TOTAL', 'count': 56616799, 'amount': 69687350676.0}]},
  {'name': 'nadia district',
   'metric': [{'type': 'TOTAL', 'count': 65274337, 'amount': 107932013030.0}]},
  {'name': 'birbhum district',
   'metric': [{'type': 'TOTAL', 'count': 36905213, 'amount': 57787007226.0}]},
  {'name': 'purba medinipur district',
   'metric': [{'type': 'TOTAL',
     'count': 67833775,
     'amount': 114277126269.0}]}]}

In [48]:
E["data"]["hoverDataList"]

[{'name': 'south twenty four parganas district',
  'metric': [{'type': 'TOTAL', 'count': 76936211, 'amount': 118552623594.0}]},
 {'name': 'purba bardhaman district',
  'metric': [{'type': 'TOTAL', 'count': 43690070, 'amount': 70602865584.0}]},
 {'name': 'uttar dinajpur district',
  'metric': [{'type': 'TOTAL', 'count': 37198721, 'amount': 61950132057.0}]},
 {'name': 'kalimpong district',
  'metric': [{'type': 'TOTAL', 'count': 1847818, 'amount': 2646924444.0}]},
 {'name': 'murshidabad district',
  'metric': [{'type': 'TOTAL', 'count': 88522023, 'amount': 156002264967.0}]},
 {'name': 'paschim medinipur district',
  'metric': [{'type': 'TOTAL', 'count': 58238212, 'amount': 84317739854.0}]},
 {'name': 'dakshin dinajpur district',
  'metric': [{'type': 'TOTAL', 'count': 13106067, 'amount': 21452200306.0}]},
 {'name': 'jalpaiguri district',
  'metric': [{'type': 'TOTAL', 'count': 20696406, 'amount': 27260366555.0}]},
 {'name': 'purulia district',
  'metric': [{'type': 'TOTAL', 'count': 24755604, 'amount': 26562481159.0}]},
 {'name': 'north twenty four parganas district',
  'metric': [{'type': 'TOTAL', 'count': 199005333, 'amount': 256651022725.0}]},
 {'name': 'bankura district',
  'metric': [{'type': 'TOTAL', 'count': 27187898, 'amount': 38703687103.0}]},
 {'name': 'jhargram district',
  'metric': [{'type': 'TOTAL', 'count': 8887423, 'amount': 11463658026.0}]},
 {'name': 'darjeeling district',
  'metric': [{'type': 'TOTAL', 'count': 27795067, 'amount': 40187454877.0}]},
 {'name': 'cooch behar district',
  'metric': [{'type': 'TOTAL', 'count': 33080526, 'amount': 42135373824.0}]},
 {'name': 'malda district',
  'metric': [{'type': 'TOTAL', 'count': 63424613, 'amount': 102421242316.0}]},
 {'name': 'howrah district',
  'metric': [{'type': 'TOTAL', 'count': 67496284, 'amount': 102576375745.0}]},
 {'name': 'hooghly district',
  'metric': [{'type': 'TOTAL', 'count': 59676576, 'amount': 90713828065.0}]},
 {'name': 'kolkata district',
  'metric': [{'type': 'TOTAL', 'count': 133085069, 'amount': 185223784274.0}]},
 {'name': 'alipurduar district',
  'metric': [{'type': 'TOTAL', 'count': 15875637, 'amount': 20992506730.0}]},
 {'name': 'paschim bardhaman district',
  'metric': [{'type': 'TOTAL', 'count': 56616799, 'amount': 69687350676.0}]},
 {'name': 'nadia district',
  'metric': [{'type': 'TOTAL', 'count': 65274337, 'amount': 107932013030.0}]},
 {'name': 'birbhum district',
  'metric': [{'type': 'TOTAL', 'count': 36905213, 'amount': 57787007226.0}]},
 {'name': 'purba medinipur district',
  'metric': [{'type': 'TOTAL', 'count': 67833775, 'amount': 114277126269.0}]}]

In [49]:
print(E["data"]["hoverDataList"][0]["name"])
print(E["data"]["hoverDataList"][0])
print(E["data"]["hoverDataList"][0]["metric"][0]["count"])
print(E["data"]["hoverDataList"][0]["metric"][0]["amount"])

south twenty four parganas district
{'name': 'south twenty four parganas district', 'metric': [{'type': 'TOTAL', 'count': 76936211, 'amount': 118552623594.0}]}
76936211
118552623594.0

In [50]:
#Map_Transaction
path5="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/map/transaction/hover/country/india/state/"
map_transaction_list = os.listdir(path5)
columns5={"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_Count":[], "Transaction_amount":[]}

for state in map_transaction_list:
    current_states = path5 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            E=json.load(data)
            try:
                for i in E["data"]["hoverDataList"]:
                    name=i["name"]
                    count=i["metric"][0]["count"]
                    amount=i["metric"][0]["amount"]
                    columns5["Districts"].append(name)
                    columns5["Transaction_Count"].append(count)
                    columns5["Transaction_amount"].append(amount)
                    columns5["States"].append(state)
                    columns5["Years"].append(year)
                    columns5["Quarter"].append(int(file.strip(".json")))
            except:
                pass

In [51]:
columns5

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',

In [52]:
map_transaction = pd.DataFrame(columns5)
map_transaction

,States,Years,Quarter,Districts,Transaction_Count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [53]:
map_transaction["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [54]:
map_transaction["States"]= map_transaction["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
map_transaction["States"]= map_transaction["States"].str.replace("-", " ")
map_transaction["States"]= map_transaction["States"].str.title()
map_transaction["States"]= map_transaction["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [55]:
map_transaction["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Map User

In [56]:
#Map_User
path6="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path6)
columns6={"States":[], "Years":[], "Quarter":[], "Districts":[], "Registered_Users":[], "App_Opens":[]}

for state in map_user_list:
    current_states = path6 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            F=json.load(data)

In [57]:
print(F)

{'success': True, 'code': 'SUCCESS', 'data': {'hoverData': {'south twenty four parganas district': {'registeredUsers': 2525913, 'appOpens': 148514597}, 'purba bardhaman district': {'registeredUsers': 1435548, 'appOpens': 84180749}, 'uttar dinajpur district': {'registeredUsers': 922938, 'appOpens': 66212953}, 'kalimpong district': {'registeredUsers': 78277, 'appOpens': 4244012}, 'murshidabad district': {'registeredUsers': 2463675, 'appOpens': 165497019}, 'paschim medinipur district': {'registeredUsers': 1522845, 'appOpens': 80731143}, 'dakshin dinajpur district': {'registeredUsers': 489732, 'appOpens': 30374022}, 'jalpaiguri district': {'registeredUsers': 647266, 'appOpens': 42531734}, 'purulia district': {'registeredUsers': 809355, 'appOpens': 56448658}, 'north twenty four parganas district': {'registeredUsers': 5085095, 'appOpens': 234840305}, 'bankura district': {'registeredUsers': 1017304, 'appOpens': 49393224}, 'jhargram district': {'registeredUsers': 282208, 'appOpens': 14361554}, 'darjeeling district': {'registeredUsers': 881187, 'appOpens': 56941907}, 'cooch behar district': {'registeredUsers': 932485, 'appOpens': 53702834}, 'malda district': {'registeredUsers': 1444985, 'appOpens': 122226269}, 'howrah district': {'registeredUsers': 2140752, 'appOpens': 116704834}, 'hooghly district': {'registeredUsers': 1957356, 'appOpens': 96383119}, 'kolkata district': {'registeredUsers': 3476288, 'appOpens': 178709399}, 'alipurduar district': {'registeredUsers': 475688, 'appOpens': 31842355}, 'paschim bardhaman district': {'registeredUsers': 1468252, 'appOpens': 80543469}, 'nadia district': {'registeredUsers': 1861738, 'appOpens': 98740305}, 'birbhum district': {'registeredUsers': 1114220, 'appOpens': 73465525}, 'purba medinipur district': {'registeredUsers': 1717074, 'appOpens': 108350777}}}, 'responseTimestamp': 1739974567116}

In [58]:
print(F["data"]["hoverData"])

{'south twenty four parganas district': {'registeredUsers': 2525913, 'appOpens': 148514597}, 'purba bardhaman district': {'registeredUsers': 1435548, 'appOpens': 84180749}, 'uttar dinajpur district': {'registeredUsers': 922938, 'appOpens': 66212953}, 'kalimpong district': {'registeredUsers': 78277, 'appOpens': 4244012}, 'murshidabad district': {'registeredUsers': 2463675, 'appOpens': 165497019}, 'paschim medinipur district': {'registeredUsers': 1522845, 'appOpens': 80731143}, 'dakshin dinajpur district': {'registeredUsers': 489732, 'appOpens': 30374022}, 'jalpaiguri district': {'registeredUsers': 647266, 'appOpens': 42531734}, 'purulia district': {'registeredUsers': 809355, 'appOpens': 56448658}, 'north twenty four parganas district': {'registeredUsers': 5085095, 'appOpens': 234840305}, 'bankura district': {'registeredUsers': 1017304, 'appOpens': 49393224}, 'jhargram district': {'registeredUsers': 282208, 'appOpens': 14361554}, 'darjeeling district': {'registeredUsers': 881187, 'appOpens': 56941907}, 'cooch behar district': {'registeredUsers': 932485, 'appOpens': 53702834}, 'malda district': {'registeredUsers': 1444985, 'appOpens': 122226269}, 'howrah district': {'registeredUsers': 2140752, 'appOpens': 116704834}, 'hooghly district': {'registeredUsers': 1957356, 'appOpens': 96383119}, 'kolkata district': {'registeredUsers': 3476288, 'appOpens': 178709399}, 'alipurduar district': {'registeredUsers': 475688, 'appOpens': 31842355}, 'paschim bardhaman district': {'registeredUsers': 1468252, 'appOpens': 80543469}, 'nadia district': {'registeredUsers': 1861738, 'appOpens': 98740305}, 'birbhum district': {'registeredUsers': 1114220, 'appOpens': 73465525}, 'purba medinipur district': {'registeredUsers': 1717074, 'appOpens': 108350777}}

In [59]:
for i in F["data"]["hoverData"].items():
    print(i)

('south twenty four parganas district', {'registeredUsers': 2525913, 'appOpens': 148514597})
('purba bardhaman district', {'registeredUsers': 1435548, 'appOpens': 84180749})
('uttar dinajpur district', {'registeredUsers': 922938, 'appOpens': 66212953})
('kalimpong district', {'registeredUsers': 78277, 'appOpens': 4244012})
('murshidabad district', {'registeredUsers': 2463675, 'appOpens': 165497019})
('paschim medinipur district', {'registeredUsers': 1522845, 'appOpens': 80731143})
('dakshin dinajpur district', {'registeredUsers': 489732, 'appOpens': 30374022})
('jalpaiguri district', {'registeredUsers': 647266, 'appOpens': 42531734})
('purulia district', {'registeredUsers': 809355, 'appOpens': 56448658})
('north twenty four parganas district', {'registeredUsers': 5085095, 'appOpens': 234840305})
('bankura district', {'registeredUsers': 1017304, 'appOpens': 49393224})
('jhargram district', {'registeredUsers': 282208, 'appOpens': 14361554})
('darjeeling district', {'registeredUsers': 881187, 'appOpens': 56941907})
('cooch behar district', {'registeredUsers': 932485, 'appOpens': 53702834})
('malda district', {'registeredUsers': 1444985, 'appOpens': 122226269})
('howrah district', {'registeredUsers': 2140752, 'appOpens': 116704834})
('hooghly district', {'registeredUsers': 1957356, 'appOpens': 96383119})
('kolkata district', {'registeredUsers': 3476288, 'appOpens': 178709399})
('alipurduar district', {'registeredUsers': 475688, 'appOpens': 31842355})
('paschim bardhaman district', {'registeredUsers': 1468252, 'appOpens': 80543469})
('nadia district', {'registeredUsers': 1861738, 'appOpens': 98740305})
('birbhum district', {'registeredUsers': 1114220, 'appOpens': 73465525})
('purba medinipur district', {'registeredUsers': 1717074, 'appOpens': 108350777})

In [60]:
for i in F["data"]["hoverData"].items():
    print(i[0])

south twenty four parganas district
purba bardhaman district
uttar dinajpur district
kalimpong district
murshidabad district
paschim medinipur district
dakshin dinajpur district
jalpaiguri district
purulia district
north twenty four parganas district
bankura district
jhargram district
darjeeling district
cooch behar district
malda district
howrah district
hooghly district
kolkata district
alipurduar district
paschim bardhaman district
nadia district
birbhum district
purba medinipur district

In [61]:
for i in F["data"]["hoverData"].items():
    print(i[1])

{'registeredUsers': 2525913, 'appOpens': 148514597}
{'registeredUsers': 1435548, 'appOpens': 84180749}
{'registeredUsers': 922938, 'appOpens': 66212953}
{'registeredUsers': 78277, 'appOpens': 4244012}
{'registeredUsers': 2463675, 'appOpens': 165497019}
{'registeredUsers': 1522845, 'appOpens': 80731143}
{'registeredUsers': 489732, 'appOpens': 30374022}
{'registeredUsers': 647266, 'appOpens': 42531734}
{'registeredUsers': 809355, 'appOpens': 56448658}
{'registeredUsers': 5085095, 'appOpens': 234840305}
{'registeredUsers': 1017304, 'appOpens': 49393224}
{'registeredUsers': 282208, 'appOpens': 14361554}
{'registeredUsers': 881187, 'appOpens': 56941907}
{'registeredUsers': 932485, 'appOpens': 53702834}
{'registeredUsers': 1444985, 'appOpens': 122226269}
{'registeredUsers': 2140752, 'appOpens': 116704834}
{'registeredUsers': 1957356, 'appOpens': 96383119}
{'registeredUsers': 3476288, 'appOpens': 178709399}
{'registeredUsers': 475688, 'appOpens': 31842355}
{'registeredUsers': 1468252, 'appOpens': 80543469}
{'registeredUsers': 1861738, 'appOpens': 98740305}
{'registeredUsers': 1114220, 'appOpens': 73465525}
{'registeredUsers': 1717074, 'appOpens': 108350777}

In [62]:
for i in F["data"]["hoverData"].items():
    print(i[1]["registeredUsers"])

2525913
1435548
922938
78277
2463675
1522845
489732
647266
809355
5085095
1017304
282208
881187
932485
1444985
2140752
1957356
3476288
475688
1468252
1861738
1114220
1717074

In [63]:
for i in F["data"]["hoverData"].items():
    print(i[1]["appOpens"])

148514597
84180749
66212953
4244012
165497019
80731143
30374022
42531734
56448658
234840305
49393224
14361554
56941907
53702834
122226269
116704834
96383119
178709399
31842355
80543469
98740305
73465525
108350777

In [64]:
for i in F["data"]["hoverData"].items():
    district=i[0]
    registeredusers=i[1]["registeredUsers"]
    appopens=i[1]["appOpens"]
    columns6["Districts"].append(district)
    columns6["Registered_Users"].append(registeredusers)
    columns6["App_Opens"].append(appopens)
    columns6["States"].append(state)
    columns6["Years"].append(year)
    columns6["Quarter"].append(int(file.strip(".json")))

In [65]:
#Map_User
path6="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path6)
columns6={"States":[], "Years":[], "Quarter":[], "Districts":[], "Registered_Users":[], "App_Opens":[]}

for state in map_user_list:
    current_states = path6 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            F=json.load(data)
            for i in F["data"]["hoverData"].items():
                district=i[0]
                registeredusers=i[1]["registeredUsers"]
                appopens=i[1]["appOpens"]
                columns6["Districts"].append(district)
                columns6["Registered_Users"].append(registeredusers)
                columns6["App_Opens"].append(appopens)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

In [66]:
columns6

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',

In [67]:
map_user = pd.DataFrame(columns6)
map_user

,States,Years,Quarter,Districts,Registered_Users,App_Opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [68]:
map_user["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [69]:
map_user["States"]= map_user["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
map_user["States"]= map_user["States"].str.replace("-", " ")
map_user["States"]= map_user["States"].str.title()
map_user["States"]= map_user["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [70]:
map_user["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Top Insurance

In [71]:
#Top_Insurance
path7="C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/top/insurance/country/india/state/"
top_ins_list = os.listdir(path7)
columns7={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_Count":[], "Transaction_amount":[]}

for state in top_ins_list:
    current_states = path7 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            G=json.load(data)
            for i in G["data"]["pincodes"]:
                entityname=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                columns7["Pincodes"].append(entityname)
                columns7["Transaction_Count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))

In [72]:
columns7

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'assam',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'bihar',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  'chandigarh',
  ...],
 'Years': ['2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2020',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2021',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',
  '2022',

In [73]:
top_insurance = pd.DataFrame(columns7)
top_insurance

,States,Years,Quarter,Pincodes,Transaction_Count,Transaction_amount
0,andaman-&-nicobar-islands,2020,2,744301,3,565.0
1,andaman-&-nicobar-islands,2020,2,744104,2,513.0
2,andaman-&-nicobar-islands,2020,2,744101,1,282.0
3,andaman-&-nicobar-islands,2020,3,744112,9,3432.0
4,andaman-&-nicobar-islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,west-bengal,2024,4,711101,713,750354.0
6664,west-bengal,2024,4,700091,642,969634.0
6665,west-bengal,2024,4,700150,627,761501.0
6666,west-bengal,2024,4,700039,619,787836.0
6667,west-bengal,2024,4,700156,574,888613.0

In [74]:
top_insurance["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [75]:
top_insurance["States"]= top_insurance["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
top_insurance["States"]= top_insurance["States"].str.replace("-", " ")
top_insurance["States"]= top_insurance["States"].str.title()
top_insurance["States"]= top_insurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [76]:
top_insurance["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Top Transaction

In [77]:
#Top transaction
path8 = "C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/top/transaction/country/india/state/"
top_trans_list = os.listdir(path8)

columns8={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_Count":[], "Transaction_amount":[]}

for state in top_trans_list:
    current_states = path8 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            H=json.load(data)
            for i in H["data"]["pincodes"]:
                entityname=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                columns8["Pincodes"].append(entityname)
                columns8["Transaction_Count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

In [78]:
columns8

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',

In [79]:
top_transaction = pd.DataFrame(columns8)
top_transaction

,States,Years,Quarter,Pincodes,Transaction_Count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,744101,1622,2.769298e+06
1,andaman-&-nicobar-islands,2018,1,744103,1223,2.238042e+06
2,andaman-&-nicobar-islands,2018,1,744102,969,3.519060e+06
3,andaman-&-nicobar-islands,2018,1,744105,685,1.298561e+06
4,andaman-&-nicobar-islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,west-bengal,2024,4,711101,6753348,1.049483e+10
9995,west-bengal,2024,4,700059,6662715,8.009476e+09
9996,west-bengal,2024,4,700039,6575693,9.018748e+09
9997,west-bengal,2024,4,734001,6432082,8.996529e+09
9998,west-bengal,2024,4,733134,6313560,1.050259e+10

In [80]:
top_transaction["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [81]:
top_transaction["States"]= top_transaction["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
top_transaction["States"]= top_transaction["States"].str.replace("-", " ")
top_transaction["States"]= top_transaction["States"].str.title()
top_transaction["States"]= top_transaction["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [82]:
top_transaction["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# Top User

In [83]:
#Top User
path9 = "C:/Users/Administrator/Desktop/Phonepe_pulse_data_visulization/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path9)

columns9={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUsers":[]}

for state in top_user_list:
    current_states = path9 + state + "/"
    aggre_year_list=os.listdir(current_states)

    for year in aggre_year_list:
        current_year=current_states + year + "/"
        aggre_file_list=os.listdir(current_year)

        for file in aggre_file_list:
            current_file=current_year + file
            data=open(current_file,"r")
            I=json.load(data)
            for i in I["data"]["pincodes"]:
                entityname=i["name"]
                registeredusers=i["registeredUsers"]
                columns9["Pincodes"].append(entityname)
                columns9["RegisteredUsers"].append(registeredusers)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

In [84]:
columns9

{'States': ['andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andaman-&-nicobar-islands',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'andhra-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',
  'arunachal-pradesh',

In [85]:
top_user = pd.DataFrame(columns9)
top_user

                         States Years  Quarter Pincodes  RegisteredUsers
0     andaman-&-nicobar-islands  2018        1   744103             1608
1     andaman-&-nicobar-islands  2018        1   744101             1108
2     andaman-&-nicobar-islands  2018        1   744105             1075
3     andaman-&-nicobar-islands  2018        1   744102             1006
4     andaman-&-nicobar-islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                west-bengal  2024        4   733134           169596
9996                west-bengal  2024        4   700059           169448
9997                west-bengal  2024        4   711302           146034
9998                west-bengal  2024        4   700150           142151
9999                west-bengal  2024        4   711106           142077

[10000 rows x 5 columns]

In [86]:
top_user["States"].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [87]:
top_user["States"]= top_user["States"].str.replace('andaman-&-nicobar-islands', 'Andaman & Nicobar')
top_user["States"]= top_user["States"].str.replace("-", " ")
top_user["States"]= top_user["States"].str.title()
top_user["States"]= top_user["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu', "Dadra and Nagar Haveli and Daman and Diu")

In [88]:
top_user["States"].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

# PostgreSQL

### Store_aggregated_insurance

In [89]:
aggregated_insurance.columns

Index(['States', 'Years', 'Quarter', 'Transaction_Type', 'Transaction_Count',
       'Transactions_amount'],
      dtype='str')

In [90]:
aggregated_insurance.values

array([['Andaman & Nicobar', '2020', 2, 'Insurance', 6, 1360.0],
       ['Andaman & Nicobar', '2020', 3, 'Insurance', 41, 15380.0],
       ['Andaman & Nicobar', '2020', 4, 'Insurance', 124, 157975.0],
       ...,
       ['West Bengal', '2024', 2, 'Insurance', 67048, 89476633.0],
       ['West Bengal', '2024', 3, 'Insurance', 77158, 107451766.0],
       ['West Bengal', '2024', 4, 'Insurance', 91719, 120602777.0]],
      shape=(682, 6), dtype=object)

In [91]:
aggregated_insurance.values.tolist()

[['Andaman & Nicobar', '2020', 2, 'Insurance', 6, 1360.0],
 ['Andaman & Nicobar', '2020', 3, 'Insurance', 41, 15380.0],
 ['Andaman & Nicobar', '2020', 4, 'Insurance', 124, 157975.0],
 ['Andaman & Nicobar', '2021', 1, 'Insurance', 225, 244266.0],
 ['Andaman & Nicobar', '2021', 2, 'Insurance', 137, 181504.0],
 ['Andaman & Nicobar', '2021', 3, 'Insurance', 230, 305235.0],
 ['Andaman & Nicobar', '2021', 4, 'Insurance', 757, 1056380.0],
 ['Andaman & Nicobar', '2022', 1, 'Insurance', 768, 1131287.0],
 ['Andaman & Nicobar', '2022', 2, 'Insurance', 501, 779740.0],
 ['Andaman & Nicobar', '2022', 3, 'Insurance', 643, 902466.0],
 ['Andaman & Nicobar', '2022', 4, 'Insurance', 901, 1441210.0],
 ['Andaman & Nicobar', '2023', 1, 'Insurance', 1004, 1439198.0],
 ['Andaman & Nicobar', '2023', 2, 'Insurance', 768, 1233395.0],
 ['Andaman & Nicobar', '2023', 3, 'Insurance', 795, 1251145.0],
 ['Andaman & Nicobar', '2023', 4, 'Insurance', 1145, 1757821.0],
 ['Andaman & Nicobar', '2024', 1, 'Insurance', 1371, 1964556.0],
 ['Andaman & Nicobar', '2024', 2, 'Insurance', 1097, 1744694.0],
 ['Andaman & Nicobar', '2024', 3, 'Insurance', 1191, 1752800.0],
 ['Andaman & Nicobar', '2024', 4, 'Insurance', 1293, 2026380.0],
 ['Andhra Pradesh', '2020', 2, 'Insurance', 22104, 3982391.0],
 ['Andhra Pradesh', '2020', 3, 'Insurance', 49812, 12426481.0],
 ['Andhra Pradesh', '2020', 4, 'Insurance', 21464, 12985632.0],
 ['Andhra Pradesh', '2021', 1, 'Insurance', 22105, 12749874.0],
 ['Andhra Pradesh', '2021', 2, 'Insurance', 33205, 22730687.0],
 ['Andhra Pradesh', '2021', 3, 'Insurance', 23075, 19914338.0],
 ['Andhra Pradesh', '2021', 4, 'Insurance', 25423, 31610335.0],
 ['Andhra Pradesh', '2022', 1, 'Insurance', 29954, 42648157.0],
 ['Andhra Pradesh', '2022', 2, 'Insurance', 32185, 41708072.0],
 ['Andhra Pradesh', '2022', 3, 'Insurance', 39301, 48791931.0],
 ['Andhra Pradesh', '2022', 4, 'Insurance', 44329, 58043239.0],
 ['Andhra Pradesh', '2023', 1, 'Insurance', 34920, 51963355.0],
 ['Andhra Pradesh', '2023', 2, 'Insurance', 36376, 52067478.0],
 ['Andhra Pradesh', '2023', 3, 'Insurance', 43150, 57802396.0],
 ['Andhra Pradesh', '2023', 4, 'Insurance', 41798, 62342423.0],
 ['Andhra Pradesh', '2024', 1, 'Insurance', 46582, 63563802.0],
 ['Andhra Pradesh', '2024', 2, 'Insurance', 42547, 62948281.0],
 ['Andhra Pradesh', '2024', 3, 'Insurance', 48014, 73915199.0],
 ['Andhra Pradesh', '2024', 4, 'Insurance', 61425, 80028914.0],
 ['Arunachal Pradesh', '2020', 2, 'Insurance', 65, 14329.0],
 ['Arunachal Pradesh', '2020', 3, 'Insurance', 135, 39687.0],
 ['Arunachal Pradesh', '2020', 4, 'Insurance', 125, 84247.0],
 ['Arunachal Pradesh', '2021', 1, 'Insurance', 194, 131611.0],
 ['Arunachal Pradesh', '2021', 2, 'Insurance', 204, 224928.0],
 ['Arunachal Pradesh', '2021', 3, 'Insurance', 212, 371051.0],
 ['Arunachal Pradesh', '2021', 4, 'Insurance', 320, 598459.0],
 ['Arunachal Pradesh', '2022', 1, 'Insurance', 355, 894107.0],
 ['Arunachal Pradesh', '2022', 2, 'Insurance', 564, 1360231.0],
 ['Arunachal Pradesh', '2022', 3, 'Insurance', 510, 1300304.0],
 ['Arunachal Pradesh', '2022', 4, 'Insurance', 613, 1464572.0],
 ['Arunachal Pradesh', '2023', 1, 'Insurance', 606, 1747475.0],
 ['Arunachal Pradesh', '2023', 2, 'Insurance', 696, 2095988.0],
 ['Arunachal Pradesh', '2023', 3, 'Insurance', 718, 1904786.0],
 ['Arunachal Pradesh', '2023', 4, 'Insurance', 809, 2105408.0],
 ['Arunachal Pradesh', '2024', 1, 'Insurance', 1100, 2419700.0],
 ['Arunachal Pradesh', '2024', 2, 'Insurance', 1147, 2353015.0],
 ['Arunachal Pradesh', '2024', 3, 'Insurance', 842, 1951385.0],
 ['Arunachal Pradesh', '2024', 4, 'Insurance', 999, 2359472.0],
 ['Assam', '2020', 2, 'Insurance', 978, 210034.0],
 ['Assam', '2020', 3, 'Insurance', 2206, 599450.0],
 ['Assam', '2020', 4, 'Insurance', 2413, 1806801.0],
 ['Assam', '2021', 1, 'Insurance', 3167, 2334419.0],
 ['Assam', '2021', 2, 'Insurance', 3265, 3008122.0],
 ['Assam', '2021', 3, 'Insurance', 4495, 6010865.0],
 ['Assam', '2021', 4, 'Insurance', 8622, 13962068.0],
 ['Assam', '2022', 1, 'Insurance', 16230, 27447766.0],
 ['Assam', '2022', 2, 'Insurance', 9228, 15357811.0],
 ['Assam', '2022', 3, 'Insurance', 14149, 22543564.0],
 ['Assam', '2022', 4, 'Insurance', 18826, 29239168.0],
 ['Assam', '2023', 1, 'Insurance', 22100, 36963888.0],
 ['Assam', '2023', 2, 'Insurance', 16475, 28368139.0],
 ['Assam', '2023', 3, 'Insurance', 22593, 35618158.0],
 ['Assam', '2023', 4, 'Insurance', 23168, 38731734.0],
 ['Assam', '2024', 1, 'Insurance', 33097, 48107248.0],
 ['Assam', '2024', 2, 'Insurance', 22368, 34796603.0],
 ['Assam', '2024', 3, 'Insurance', 17633, 31388971.0],
 ['Assam', '2024', 4, 'Insurance', 21805, 35336229.0],
 ['Bihar', '2020', 2, 'Insurance', 2816, 595621.0],
 ['Bihar', '2020', 3, 'Insurance', 9733, 2161102.0],
 ['Bihar', '2020', 4, 'Insurance', 9913, 7860932.0],
 ['Bihar', '2021', 1, 'Insurance', 12554, 8796619.0],
 ['Bihar', '2021', 2, 'Insurance', 14301, 13301581.0],
 ['Bihar', '2021', 3, 'Insurance', 18030, 18234941.0],
 ['Bihar', '2021', 4, 'Insurance', 22456, 27313813.0],
 ['Bihar', '2022', 1, 'Insurance', 20253, 27755736.0],
 ['Bihar', '2022', 2, 'Insurance', 21892, 28212833.0],
 ['Bihar', '2022', 3, 'Insurance', 28511, 34704251.0],
 ['Bihar', '2022', 4, 'Insurance', 33895, 43914519.0],
 ['Bihar', '2023', 1, 'Insurance', 26929, 38746711.0],
 ['Bihar', '2023', 2, 'Insurance', 29212, 40354886.0],
 ['Bihar', '2023', 3, 'Insurance', 36550, 45832355.0],
 ['Bihar', '2023', 4, 'Insurance', 41447, 57624322.0],
 ['Bihar', '2024', 1, 'Insurance', 51592, 63844442.0],
 ['Bihar', '2024', 2, 'Insurance', 49101, 65285065.0],
 ['Bihar', '2024', 3, 'Insurance', 44745, 62777286.0],
 ['Bihar', '2024', 4, 'Insurance', 62662, 83739800.0],
 ['Chandigarh', '2020', 2, 'Insurance', 149, 29537.0],
 ['Chandigarh', '2020', 3, 'Insurance', 264, 70969.0],
 ['Chandigarh', '2020', 4, 'Insurance', 200, 153341.0],
 ['Chandigarh', '2021', 1, 'Insurance', 338, 238576.0],
 ['Chandigarh', '2021', 2, 'Insurance', 378, 310943.0],
 ['Chandigarh', '2021', 3, 'Insurance', 494, 469634.0],
 ['Chandigarh', '2021', 4, 'Insurance', 710, 835813.0],
 ['Chandigarh', '2022', 1, 'Insurance', 792, 1150932.0],
 ['Chandigarh', '2022', 2, 'Insurance', 1330, 1874959.0],
 ['Chandigarh', '2022', 3, 'Insurance', 1533, 1998439.0],
 ['Chandigarh', '2022', 4, 'Insurance', 1403, 2024528.0],
 ['Chandigarh', '2023', 1, 'Insurance', 1520, 2415574.0],
 ['Chandigarh', '2023', 2, 'Insurance', 1704, 2501107.0],
 ['Chandigarh', '2023', 3, 'Insurance', 1883, 2660630.0],
 ['Chandigarh', '2023', 4, 'Insurance', 1767, 3053934.0],
 ['Chandigarh', '2024', 1, 'Insurance', 1730, 3143984.0],
 ['Chandigarh', '2024', 2, 'Insurance', 1798, 3177315.0],
 ['Chandigarh', '2024', 3, 'Insurance', 1991, 3445738.0],
 ['Chandigarh', '2024', 4, 'Insurance', 2095, 3729932.0],
 ['Chhattisgarh', '2020', 2, 'Insurance', 1346, 279005.0],
 ['Chhattisgarh', '2020', 3, 'Insurance', 4702, 1393656.0],
 ['Chhattisgarh', '2020', 4, 'Insurance', 3757, 2249901.0],
 ['Chhattisgarh', '2021', 1, 'Insurance', 4712, 2620468.0],
 ['Chhattisgarh', '2021', 2, 'Insurance', 5055, 3813417.0],
 ['Chhattisgarh', '2021', 3, 'Insurance', 4676, 3568837.0],
 ['Chhattisgarh', '2021', 4, 'Insurance', 6029, 8229039.0],
 ['Chhattisgarh', '2022', 1, 'Insurance', 6612, 10139190.0],
 ['Chhattisgarh', '2022', 2, 'Insurance', 7008, 10119964.0],
 ['Chhattisgarh', '2022', 3, 'Insurance', 8849, 12119470.0],
 ['Chhattisgarh', '2022', 4, 'Insurance', 11994, 18137856.0],
 ['Chhattisgarh', '2023', 1, 'Insurance', 10460, 16577191.0],
 ['Chhattisgarh', '2023', 2, 'Insurance', 10514, 16389610.0],
 ['Chhattisgarh', '2023', 3, 'Insurance', 11927, 17838382.0],
 ['Chhattisgarh', '2023', 4, 'Insurance', 17300, 29704673.0],
 ['Chhattisgarh', '2024', 1, 'Insurance', 19579, 30083259.0],
 ['Chhattisgarh', '2024', 2, 'Insurance', 15724, 25935743.0],
 ['Chhattisgarh', '2024', 3, 'Insurance', 16550, 27724060.0],
 ['Chhattisgarh', '2024', 4, 'Insurance', 22723, 37421165.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2020',
  2,
  'Insurance',
  651,
  101029.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2020',
  3,
  'Insurance',
  257,
  65504.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2020',
  4,
  'Insurance',
  232,
  149513.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  1,
  'Insurance',
  467,
  285691.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  2,
  'Insurance',
  368,
  275638.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  3,
  'Insurance',
  360,
  273596.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  4,
  'Insurance',
  421,
  425384.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  1,
  'Insurance',
  493,
  720741.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  2,
  'Insurance',
  438,
  686857.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  3,
  'Insurance',
  707,
  983776.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  4,
  'Insurance',
  871,
  1272628.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  1,
  'Insurance',
  799,
  1215168.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  2,
  'Insurance',
  694,
  1058753.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  3,
  'Insurance',
  969,
  1333103.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  4,
  'Insurance',
  1207,
  1973867.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2024',
  1,
  'Insurance',
  1295,
  1908509.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2024',
  2,
  'Insurance',
  1008,
  1367259.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2024',
  3,
  'Insurance',
  1052,
  1602869.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2024',
  4,
  'Insurance',
  1503,
  2292529.0],
 ['Delhi', '2020', 2, 'Insurance', 11716, 1897480.0],
 ['Delhi', '2020', 3, 'Insurance', 7588, 1927285.0],
 ['Delhi', '2020', 4, 'Insurance', 9725, 8045442.0],
 ['Delhi', '2021', 1, 'Insurance', 12822, 9655261.0],
 ['Delhi', '2021', 2, 'Insurance', 13292, 10840929.0],
 ['Delhi', '2021', 3, 'Insurance', 16679, 15007079.0],
 ['Delhi', '2021', 4, 'Insurance', 34251, 36578331.0],
 ['Delhi', '2022', 1, 'Insurance', 28232, 35442069.0],
 ['Delhi', '2022', 2, 'Insurance', 26378, 31787281.0],
 ['Delhi', '2022', 3, 'Insurance', 35944, 41570160.0],
 ['Delhi', '2022', 4, 'Insurance', 48908, 60603173.0],
 ['Delhi', '2023', 1, 'Insurance', 45821, 61040038.0],
 ['Delhi', '2023', 2, 'Insurance', 41358, 54951108.0],
 ['Delhi', '2023', 3, 'Insurance', 47113, 58878500.0],
 ['Delhi', '2023', 4, 'Insurance', 56336, 77332401.0],
 ['Delhi', '2024', 1, 'Insurance', 53050, 76232346.0],
 ['Delhi', '2024', 2, 'Insurance', 46189, 68046072.0],
 ['Delhi', '2024', 3, 'Insurance', 49150, 71139489.0],
 ['Delhi', '2024', 4, 'Insurance', 67962, 94390728.0],
 ['Goa', '2020', 2, 'Insurance', 341, 71100.0],
 ['Goa', '2020', 3, 'Insurance', 683, 196864.0],
 ['Goa', '2020', 4, 'Insurance', 614, 682364.0],
 ['Goa', '2021', 1, 'Insurance', 879, 827384.0],
 ['Goa', '2021', 2, 'Insurance', 1016, 1028339.0],
 ['Goa', '2021', 3, 'Insurance', 1214, 1385986.0],
 ['Goa', '2021', 4, 'Insurance', 2087, 2737316.0],
 ['Goa', '2022', 1, 'Insurance', 2634, 3865245.0],
 ['Goa', '2022', 2, 'Insurance', 3524, 5093510.0],
 ['Goa', '2022', 3, 'Insurance', 3157, 4142108.0],
 ['Goa', '2022', 4, 'Insurance', 4388, 6190669.0],
 ['Goa', '2023', 1, 'Insurance', 4097, 5859549.0],
 ['Goa', '2023', 2, 'Insurance', 4166, 5930801.0],
 ['Goa', '2023', 3, 'Insurance', 3927, 5646054.0],
 ['Goa', '2023', 4, 'Insurance', 4883, 7411001.0],
 ['Goa', '2024', 1, 'Insurance', 5225, 7528093.0],
 ['Goa', '2024', 2, 'Insurance', 5021, 7178558.0],
 ['Goa', '2024', 3, 'Insurance', 5354, 8051690.0],
 ['Goa', '2024', 4, 'Insurance', 6662, 9903374.0],
 ['Gujarat', '2020', 2, 'Insurance', 7697, 1430591.0],
 ['Gujarat', '2020', 3, 'Insurance', 12525, 3335812.0],
 ['Gujarat', '2020', 4, 'Insurance', 9990, 6055037.0],
 ['Gujarat', '2021', 1, 'Insurance', 12673, 7288104.0],
 ['Gujarat', '2021', 2, 'Insurance', 14676, 10263998.0],
 ['Gujarat', '2021', 3, 'Insurance', 15348, 12341903.0],
 ['Gujarat', '2021', 4, 'Insurance', 19142, 23282921.0],
 ['Gujarat', '2022', 1, 'Insurance', 22221, 29953433.0],
 ['Gujarat', '2022', 2, 'Insurance', 25381, 32090965.0],
 ['Gujarat', '2022', 3, 'Insurance', 31302, 37557227.0],
 ['Gujarat', '2022', 4, 'Insurance', 36418, 50629325.0],
 ['Gujarat', '2023', 1, 'Insurance', 32600, 46937694.0],
 ['Gujarat', '2023', 2, 'Insurance', 32484, 46254095.0],
 ['Gujarat', '2023', 3, 'Insurance', 51049, 65768085.0],
 ['Gujarat', '2023', 4, 'Insurance', 41128, 66735446.0],
 ['Gujarat', '2024', 1, 'Insurance', 44665, 62633910.0],
 ['Gujarat', '2024', 2, 'Insurance', 44007, 63866463.0],
 ['Gujarat', '2024', 3, 'Insurance', 46763, 70950327.0],
 ['Gujarat', '2024', 4, 'Insurance', 62526, 91858105.0],
 ['Haryana', '2020', 2, 'Insurance', 6321, 1179814.0],
 ['Haryana', '2020', 3, 'Insurance', 7139, 1884868.0],
 ['Haryana', '2020', 4, 'Insurance', 8283, 5974278.0],
 ['Haryana', '2021', 1, 'Insurance', 11038, 7297880.0],
 ['Haryana', '2021', 2, 'Insurance', 12516, 11272453.0],
 ['Haryana', '2021', 3, 'Insurance', 14163, 13215898.0],
 ['Haryana', '2021', 4, 'Insurance', 19489, 25885838.0],
 ['Haryana', '2022', 1, 'Insurance', 22783, 32526943.0],
 ['Haryana', '2022', 2, 'Insurance', 25352, 33759068.0],
 ['Haryana', '2022', 3, 'Insurance', 35346, 45402800.0],
 ['Haryana', '2022', 4, 'Insurance', 37971, 56627115.0],
 ['Haryana', '2023', 1, 'Insurance', 37287, 61127194.0],
 ['Haryana', '2023', 2, 'Insurance', 40710, 62186066.0],
 ['Haryana', '2023', 3, 'Insurance', 42815, 61782311.0],
 ['Haryana', '2023', 4, 'Insurance', 47506, 80747159.0],
 ['Haryana', '2024', 1, 'Insurance', 50391, 81816509.0],
 ['Haryana', '2024', 2, 'Insurance', 46085, 74779879.0],
 ['Haryana', '2024', 3, 'Insurance', 49735, 79198642.0],
 ['Haryana', '2024', 4, 'Insurance', 58808, 94316512.0],
 ['Himachal Pradesh', '2020', 2, 'Insurance', 392, 77936.0],
 ['Himachal Pradesh', '2020', 3, 'Insurance', 531, 165559.0],
 ['Himachal Pradesh', '2020', 4, 'Insurance', 710, 630966.0],
 ['Himachal Pradesh', '2021', 1, 'Insurance', 1064, 906492.0],
 ['Himachal Pradesh', '2021', 2, 'Insurance', 1210, 1402338.0],
 ['Himachal Pradesh', '2021', 3, 'Insurance', 1759, 2444545.0],
 ['Himachal Pradesh', '2021', 4, 'Insurance', 2474, 4667661.0],
 ['Himachal Pradesh', '2022', 1, 'Insurance', 2768, 5234739.0],
 ['Himachal Pradesh', '2022', 2, 'Insurance', 2831, 5371078.0],
 ['Himachal Pradesh', '2022', 3, 'Insurance', 3641, 6161692.0],
 ['Himachal Pradesh', '2022', 4, 'Insurance', 4565, 9060436.0],
 ['Himachal Pradesh', '2023', 1, 'Insurance', 3909, 7826133.0],
 ['Himachal Pradesh', '2023', 2, 'Insurance', 4197, 8499425.0],
 ['Himachal Pradesh', '2023', 3, 'Insurance', 3935, 7869767.0],
 ['Himachal Pradesh', '2023', 4, 'Insurance', 5211, 11898824.0],
 ['Himachal Pradesh', '2024', 1, 'Insurance', 5430, 10433254.0],
 ['Himachal Pradesh', '2024', 2, 'Insurance', 5194, 10008705.0],
 ['Himachal Pradesh', '2024', 3, 'Insurance', 5272, 10538999.0],
 ['Himachal Pradesh', '2024', 4, 'Insurance', 6697, 14090523.0],
 ['Jammu & Kashmir', '2020', 2, 'Insurance', 206, 48484.0],
 ['Jammu & Kashmir', '2020', 3, 'Insurance', 441, 133339.0],
 ['Jammu & Kashmir', '2020', 4, 'Insurance', 647, 734861.0],
 ['Jammu & Kashmir', '2021', 1, 'Insurance', 1105, 1546288.0],
 ['Jammu & Kashmir', '2021', 2, 'Insurance', 1197, 1832089.0],
 ['Jammu & Kashmir', '2021', 3, 'Insurance', 1452, 2139133.0],
 ['Jammu & Kashmir', '2021', 4, 'Insurance', 3113, 5223317.0],
 ['Jammu & Kashmir', '2022', 1, 'Insurance', 3584, 7244267.0],
 ['Jammu & Kashmir', '2022', 2, 'Insurance', 4071, 7729792.0],
 ['Jammu & Kashmir', '2022', 3, 'Insurance', 4794, 8281826.0],
 ['Jammu & Kashmir', '2022', 4, 'Insurance', 5031, 10111183.0],
 ['Jammu & Kashmir', '2023', 1, 'Insurance', 4555, 10275877.0],
 ['Jammu & Kashmir', '2023', 2, 'Insurance', 5262, 10974839.0],
 ['Jammu & Kashmir', '2023', 3, 'Insurance', 5453, 10975874.0],
 ['Jammu & Kashmir', '2023', 4, 'Insurance', 6264, 13932309.0],
 ['Jammu & Kashmir', '2024', 1, 'Insurance', 7313, 14695182.0],
 ['Jammu & Kashmir', '2024', 2, 'Insurance', 7397, 14237707.0],
 ['Jammu & Kashmir', '2024', 3, 'Insurance', 7597, 15554635.0],
 ['Jammu & Kashmir', '2024', 4, 'Insurance', 8893, 18252110.0],
 ['Jharkhand', '2020', 2, 'Insurance', 2063, 405031.0],
 ['Jharkhand', '2020', 3, 'Insurance', 5368, 1349934.0],
 ['Jharkhand', '2020', 4, 'Insurance', 3659, 2857024.0],
 ['Jharkhand', '2021', 1, 'Insurance', 4879, 3274851.0],
 ['Jharkhand', '2021', 2, 'Insurance', 5180, 5084230.0],
 ['Jharkhand', '2021', 3, 'Insurance', 6794, 7046048.0],
 ['Jharkhand', '2021', 4, 'Insurance', 8465, 11190423.0],
 ['Jharkhand', '2022', 1, 'Insurance', 9373, 13819466.0],
 ['Jharkhand', '2022', 2, 'Insurance', 9477, 13464840.0],
 ['Jharkhand', '2022', 3, 'Insurance', 14388, 18156857.0],
 ['Jharkhand', '2022', 4, 'Insurance', 16779, 23147805.0],
 ['Jharkhand', '2023', 1, 'Insurance', 16108, 23823406.0],
 ['Jharkhand', '2023', 2, 'Insurance', 16662, 23216215.0],
 ['Jharkhand', '2023', 3, 'Insurance', 19478, 25165702.0],
 ['Jharkhand', '2023', 4, 'Insurance', 22398, 33484644.0],
 ['Jharkhand', '2024', 1, 'Insurance', 24824, 34332990.0],
 ['Jharkhand', '2024', 2, 'Insurance', 22224, 32245129.0],
 ['Jharkhand', '2024', 3, 'Insurance', 23629, 34353146.0],
 ['Jharkhand', '2024', 4, 'Insurance', 29079, 42253614.0],
 ['Karnataka', '2020', 2, 'Insurance', 27358, 4794150.0],
 ['Karnataka', '2020', 3, 'Insurance', 53701, 12407394.0],
 ['Karnataka', '2020', 4, 'Insurance', 31747, 26814968.0],
 ['Karnataka', '2021', 1, 'Insurance', 37595, 30183325.0],
 ['Karnataka', '2021', 2, 'Insurance', 40969, 39501006.0],
 ['Karnataka', '2021', 3, 'Insurance', 47468, 48078366.0],
 ['Karnataka', '2021', 4, 'Insurance', 74436, 90723288.0],
 ['Karnataka', '2022', 1, 'Insurance', 95640, 130733580.0],
 ['Karnataka', '2022', 2, 'Insurance', 93385, 123228632.0],
 ['Karnataka', '2022', 3, 'Insurance', 110273, 144605784.0],
 ['Karnataka', '2022', 4, 'Insurance', 133971, 185063287.0],
 ['Karnataka', '2023', 1, 'Insurance', 127376, 186543426.0],
 ['Karnataka', '2023', 2, 'Insurance', 117232, 175704013.0],
 ['Karnataka', '2023', 3, 'Insurance', 139699, 199448538.0],
 ['Karnataka', '2023', 4, 'Insurance', 156076, 248056311.0],
 ['Karnataka', '2024', 1, 'Insurance', 169357, 264708700.0],
 ['Karnataka', '2024', 2, 'Insurance', 142599, 239304982.0],
 ['Karnataka', '2024', 3, 'Insurance', 174990, 287393291.0],
 ['Karnataka', '2024', 4, 'Insurance', 183532, 305861806.0],
 ['Kerala', '2020', 2, 'Insurance', 1588, 360216.0],
 ['Kerala', '2020', 3, 'Insurance', 8811, 2830361.0],
 ['Kerala', '2020', 4, 'Insurance', 5479, 4445525.0],
 ['Kerala', '2021', 1, 'Insurance', 5731, 5040506.0],
 ['Kerala', '2021', 2, 'Insurance', 9530, 9676588.0],
 ['Kerala', '2021', 3, 'Insurance', 10926, 13255646.0],
 ['Kerala', '2021', 4, 'Insurance', 19199, 31260319.0],
 ['Kerala', '2022', 1, 'Insurance', 37110, 64172190.0],
 ['Kerala', '2022', 2, 'Insurance', 35667, 59920203.0],
 ['Kerala', '2022', 3, 'Insurance', 54587, 85390924.0],
 ['Kerala', '2022', 4, 'Insurance', 65563, 103982997.0],
 ['Kerala', '2023', 1, 'Insurance', 62377, 101786828.0],
 ['Kerala', '2023', 2, 'Insurance', 61032, 100620604.0],
 ['Kerala', '2023', 3, 'Insurance', 66059, 110021582.0],
 ['Kerala', '2023', 4, 'Insurance', 73543, 121905046.0],
 ['Kerala', '2024', 1, 'Insurance', 73106, 115101791.0],
 ['Kerala', '2024', 2, 'Insurance', 65271, 108142369.0],
 ['Kerala', '2024', 3, 'Insurance', 79123, 131721699.0],
 ['Kerala', '2024', 4, 'Insurance', 89533, 144083113.0],
 ['Ladakh', '2020', 2, 'Insurance', 14, 2538.0],
 ['Ladakh', '2020', 3, 'Insurance', 33, 10260.0],
 ['Ladakh', '2020', 4, 'Insurance', 27, 34206.0],
 ['Ladakh', '2021', 1, 'Insurance', 32, 34530.0],
 ['Ladakh', '2021', 2, 'Insurance', 46, 86251.0],
 ['Ladakh', '2021', 3, 'Insurance', 192, 174052.0],

In [94]:
# Table Creation
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Aggregated_Insurance_Table
create_query1 = '''CREATE TABLE IF NOT EXISTS aggregated_insurance(States varchar(255), Years int, Quarter int, Transaction_type varchar(255),
                                               Transaction_count bigint, Transaction_amount float)'''

cur.execute(create_query1)
mydb.commit()
insert_query1 = '''INSERT INTO aggregated_insurance(States, Years, Quarter, Transaction_type,
                                               Transaction_count, Transaction_amount)
                                               VALUES (%s, %s, %s, %s, %s, %s)
                                               '''
data1 = aggregated_insurance.values.tolist()
cur.executemany(insert_query1, data1)
mydb.commit()

### Store_aggregated_transaction

In [95]:
aggregated_transaction.columns

Index(['States', 'Years', 'Quarter', 'Transaction_Type', 'Transaction_Count',
       'Transactions_amount'],
      dtype='str')

In [ ]:
# Table Creation
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Aggregated_Transaction_Table
create_query2 = '''CREATE TABLE IF NOT EXISTS aggregated_transaction(States varchar(255), Years int, Quarter int, Transaction_type varchar(255),
                                               Transaction_count bigint, Transaction_amount float)'''

cur.execute(create_query2)
mydb.commit()
insert_query2 = '''INSERT INTO aggregated_transaction(States, Years, Quarter, Transaction_type,
                                               Transaction_count, Transaction_amount)
                                               VALUES (%s, %s, %s, %s, %s, %s)
                                               '''
data2 = aggregated_transaction.values.tolist()
cur.executemany(insert_query2, data2)
mydb.commit()

### Store_aggregated_user

In [97]:
aggregated_user.columns

Index(['States', 'Years', 'Quarter', 'Brands', 'Transaction_Count',
       'Percentage'],
      dtype='str')

In [98]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Aggregated_User_Table
create_query3 = '''CREATE TABLE IF NOT EXISTS aggregated_user(States varchar(255), Years int, Quarter int, Brands varchar(255),
                                               Transaction_count bigint, Percentage float)'''

cur.execute(create_query3)
mydb.commit()
insert_query3 = '''INSERT INTO aggregated_user(States, Years, Quarter, Brands,
                                               Transaction_count, Percentage)
                                               VALUES (%s, %s, %s, %s, %s, %s)
                                               '''
data3 = aggregated_user.values.tolist()
cur.executemany(insert_query3, data3)
mydb.commit()

### Store_map_insurance

In [99]:
map_insurance.columns

Index(['States', 'Years', 'Quarter', 'Districts', 'Transaction_Count',
       'Transaction_amount'],
      dtype='str')

In [102]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Map_Insurance_Table
create_query4 = '''CREATE TABLE IF NOT EXISTS map_insurance(States varchar(255), Years int, Quarter int, Districts varchar(255),
                                               Transaction_count bigint, Transaction_amount float)'''

cur.execute(create_query4)
mydb.commit()
insert_query4 = '''INSERT INTO map_insurance(States, Years, Quarter, Districts,
                                               Transaction_count, Transaction_amount)
                                               VALUES (%s, %s, %s, %s, %s, %s)
                                               '''
data4 = map_insurance.values.tolist()
cur.executemany(insert_query4, data4)
mydb.commit()

### Store_map_transaction

In [101]:
map_transaction.columns

Index(['States', 'Years', 'Quarter', 'Districts', 'Transaction_Count',
       'Transaction_amount'],
      dtype='str')

In [103]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Map_transaction_Table
create_query5 = '''CREATE TABLE IF NOT EXISTS map_transaction(States varchar(255), Years int, Quarter int, Districts varchar(255),
                                               Transaction_count bigint, Transaction_amount float)'''

cur.execute(create_query5)
mydb.commit()
insert_query5 = '''INSERT INTO map_transaction(States, Years, Quarter, Districts,
                                               Transaction_count, Transaction_amount)
                                               VALUES (%s, %s, %s, %s, %s, %s)
                                               '''
data5 = map_transaction.values.tolist()
cur.executemany(insert_query5, data5)
mydb.commit()

### Store_map_user

In [104]:
map_user.columns

Index(['States', 'Years', 'Quarter', 'Districts', 'Registered_Users',
       'App_Opens'],
      dtype='str')

In [107]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Map_user_Table
create_query6 = '''CREATE TABLE IF NOT EXISTS map_user(States varchar(255), Years int, Quarter int, Districts varchar(255),
                                               Registered_Users bigint, App_Opens bigint)'''

cur.execute(create_query6)
mydb.commit()
insert_query6 = '''INSERT INTO map_user(States, Years, Quarter, Districts,
                                               Registered_Users, App_Opens)
                                               VALUES (%s, %s, %s, %s, %s, %s)
                                               '''
data6 = map_user.values.tolist()
cur.executemany(insert_query6, data6)
mydb.commit()

### Store_Top_insurance

In [106]:
top_insurance.columns

Index(['States', 'Years', 'Quarter', 'Pincodes', 'Transaction_Count',
       'Transaction_amount'],
      dtype='str')

In [110]:
top_insurance.values.tolist()

[['Andaman & Nicobar', '2020', 2, '744301', 3, 565.0],
 ['Andaman & Nicobar', '2020', 2, '744104', 2, 513.0],
 ['Andaman & Nicobar', '2020', 2, '744101', 1, 282.0],
 ['Andaman & Nicobar', '2020', 3, '744112', 9, 3432.0],
 ['Andaman & Nicobar', '2020', 3, '744105', 7, 3948.0],
 ['Andaman & Nicobar', '2020', 3, '744101', 5, 2194.0],
 ['Andaman & Nicobar', '2020', 3, '744206', 4, 1620.0],
 ['Andaman & Nicobar', '2020', 3, '744107', 3, 1095.0],
 ['Andaman & Nicobar', '2020', 3, '744103', 3, 947.0],
 ['Andaman & Nicobar', '2020', 3, '744302', 3, 562.0],
 ['Andaman & Nicobar', '2020', 3, '744211', 2, 101.0],
 ['Andaman & Nicobar', '2020', 3, '744301', 2, 886.0],
 ['Andaman & Nicobar', '2020', 3, '744102', 2, 314.0],
 ['Andaman & Nicobar', '2020', 4, '744105', 25, 25659.0],
 ['Andaman & Nicobar', '2020', 4, '744101', 23, 29686.0],
 ['Andaman & Nicobar', '2020', 4, '744103', 18, 24904.0],
 ['Andaman & Nicobar', '2020', 4, '744102', 17, 25073.0],
 ['Andaman & Nicobar', '2020', 4, '744112', 8, 10459.0],
 ['Andaman & Nicobar', '2020', 4, '744106', 6, 4840.0],
 ['Andaman & Nicobar', '2020', 4, '744204', 6, 11659.0],
 ['Andaman & Nicobar', '2020', 4, '744104', 4, 10271.0],
 ['Andaman & Nicobar', '2020', 4, '744206', 3, 100.0],
 ['Andaman & Nicobar', '2020', 4, '744205', 3, 5235.0],
 ['Andaman & Nicobar', '2021', 1, '744105', 47, 53060.0],
 ['Andaman & Nicobar', '2021', 1, '744103', 35, 39985.0],
 ['Andaman & Nicobar', '2021', 1, '744101', 33, 24571.0],
 ['Andaman & Nicobar', '2021', 1, '744204', 25, 29635.0],
 ['Andaman & Nicobar', '2021', 1, '744202', 12, 17588.0],
 ['Andaman & Nicobar', '2021', 1, '744102', 12, 14085.0],
 ['Andaman & Nicobar', '2021', 1, '744104', 9, 7310.0],
 ['Andaman & Nicobar', '2021', 1, '744107', 8, 9253.0],
 ['Andaman & Nicobar', '2021', 1, '744205', 7, 11223.0],
 ['Andaman & Nicobar', '2021', 1, '744301', 7, 6612.0],
 ['Andaman & Nicobar', '2021', 2, '744103', 36, 33716.0],
 ['Andaman & Nicobar', '2021', 2, '744101', 17, 19787.0],
 ['Andaman & Nicobar', '2021', 2, '744105', 15, 17163.0],
 ['Andaman & Nicobar', '2021', 2, '744102', 13, 10326.0],
 ['Andaman & Nicobar', '2021', 2, '744204', 10, 10557.0],
 ['Andaman & Nicobar', '2021', 2, '744107', 8, 11459.0],
 ['Andaman & Nicobar', '2021', 2, '744202', 6, 9766.0],
 ['Andaman & Nicobar', '2021', 2, '744104', 6, 8889.0],
 ['Andaman & Nicobar', '2021', 2, '744205', 6, 12669.0],
 ['Andaman & Nicobar', '2021', 2, '744210', 4, 9430.0],
 ['Andaman & Nicobar', '2021', 3, '744105', 70, 82425.0],
 ['Andaman & Nicobar', '2021', 3, '744103', 44, 53909.0],
 ['Andaman & Nicobar', '2021', 3, '744101', 26, 29601.0],
 ['Andaman & Nicobar', '2021', 3, '744102', 14, 20616.0],
 ['Andaman & Nicobar', '2021', 3, '744204', 13, 20075.0],
 ['Andaman & Nicobar', '2021', 3, '744202', 11, 18134.0],
 ['Andaman & Nicobar', '2021', 3, '744112', 11, 14406.0],
 ['Andaman & Nicobar', '2021', 3, '744302', 8, 7247.0],
 ['Andaman & Nicobar', '2021', 3, '744107', 6, 6406.0],
 ['Andaman & Nicobar', '2021', 3, '744104', 6, 2221.0],
 ['Andaman & Nicobar', '2021', 4, '744105', 194, 232344.0],
 ['Andaman & Nicobar', '2021', 4, '744101', 159, 211326.0],
 ['Andaman & Nicobar', '2021', 4, '744103', 133, 168668.0],
 ['Andaman & Nicobar', '2021', 4, '744102', 66, 68931.0],
 ['Andaman & Nicobar', '2021', 4, '744301', 32, 53658.0],
 ['Andaman & Nicobar', '2021', 4, '744204', 31, 102213.0],
 ['Andaman & Nicobar', '2021', 4, '744104', 24, 31069.0],
 ['Andaman & Nicobar', '2021', 4, '744112', 22, 38599.0],
 ['Andaman & Nicobar', '2021', 4, '744202', 21, 23016.0],
 ['Andaman & Nicobar', '2021', 4, '744205', 13, 30437.0],
 ['Andaman & Nicobar', '2022', 1, '744103', 174, 226181.0],
 ['Andaman & Nicobar', '2022', 1, '744101', 149, 204646.0],
 ['Andaman & Nicobar', '2022', 1, '744105', 137, 218321.0],
 ['Andaman & Nicobar', '2022', 1, '744102', 102, 147402.0],
 ['Andaman & Nicobar', '2022', 1, '744112', 36, 39197.0],
 ['Andaman & Nicobar', '2022', 1, '744104', 33, 35406.0],
 ['Andaman & Nicobar', '2022', 1, '744107', 28, 36877.0],
 ['Andaman & Nicobar', '2022', 1, '744207', 19, 50799.0],
 ['Andaman & Nicobar', '2022', 1, '744301', 16, 33406.0],
 ['Andaman & Nicobar', '2022', 1, '744205', 15, 29159.0],
 ['Andaman & Nicobar', '2022', 2, '744103', 97, 156861.0],
 ['Andaman & Nicobar', '2022', 2, '744101', 87, 121168.0],
 ['Andaman & Nicobar', '2022', 2, '744105', 78, 137418.0],
 ['Andaman & Nicobar', '2022', 2, '744102', 62, 58453.0],
 ['Andaman & Nicobar', '2022', 2, '744104', 26, 32107.0],
 ['Andaman & Nicobar', '2022', 2, '744107', 22, 52244.0],
 ['Andaman & Nicobar', '2022', 2, '744211', 19, 25543.0],
 ['Andaman & Nicobar', '2022', 2, '744112', 18, 24391.0],
 ['Andaman & Nicobar', '2022', 2, '744301', 14, 28331.0],
 ['Andaman & Nicobar', '2022', 2, '744202', 13, 20817.0],
 ['Andaman & Nicobar', '2022', 3, '744103', 151, 198569.0],
 ['Andaman & Nicobar', '2022', 3, '744101', 119, 151539.0],
 ['Andaman & Nicobar', '2022', 3, '744105', 101, 106324.0],
 ['Andaman & Nicobar', '2022', 3, '744102', 76, 102757.0],
 ['Andaman & Nicobar', '2022', 3, '744104', 31, 35790.0],
 ['Andaman & Nicobar', '2022', 3, '744301', 27, 67604.0],
 ['Andaman & Nicobar', '2022', 3, '744202', 27, 53016.0],
 ['Andaman & Nicobar', '2022', 3, '744205', 17, 34250.0],
 ['Andaman & Nicobar', '2022', 3, '744107', 16, 29251.0],
 ['Andaman & Nicobar', '2022', 3, '744204', 11, 17184.0],
 ['Andaman & Nicobar', '2022', 4, '744103', 199, 299036.0],
 ['Andaman & Nicobar', '2022', 4, '744105', 166, 253344.0],
 ['Andaman & Nicobar', '2022', 4, '744101', 146, 163498.0],
 ['Andaman & Nicobar', '2022', 4, '744102', 80, 98862.0],
 ['Andaman & Nicobar', '2022', 4, '744202', 43, 68397.0],
 ['Andaman & Nicobar', '2022', 4, '744107', 38, 73829.0],
 ['Andaman & Nicobar', '2022', 4, '744104', 31, 55827.0],
 ['Andaman & Nicobar', '2022', 4, '744205', 27, 56611.0],
 ['Andaman & Nicobar', '2022', 4, '744211', 27, 59500.0],
 ['Andaman & Nicobar', '2022', 4, '744112', 25, 42024.0],
 ['Andaman & Nicobar', '2023', 1, '744103', 236, 286594.0],
 ['Andaman & Nicobar', '2023', 1, '744101', 206, 233281.0],
 ['Andaman & Nicobar', '2023', 1, '744105', 164, 256300.0],
 ['Andaman & Nicobar', '2023', 1, '744102', 117, 134841.0],
 ['Andaman & Nicobar', '2023', 1, '744107', 30, 54849.0],
 ['Andaman & Nicobar', '2023', 1, '744301', 30, 58745.0],
 ['Andaman & Nicobar', '2023', 1, '744112', 29, 49945.0],
 ['Andaman & Nicobar', '2023', 1, '744202', 29, 64193.0],
 ['Andaman & Nicobar', '2023', 1, '744205', 27, 40580.0],
 ['Andaman & Nicobar', '2023', 1, '744211', 24, 29149.0],
 ['Andaman & Nicobar', '2023', 2, '744103', 171, 341853.0],
 ['Andaman & Nicobar', '2023', 2, '744105', 166, 255069.0],
 ['Andaman & Nicobar', '2023', 2, '744101', 134, 189989.0],
 ['Andaman & Nicobar', '2023', 2, '744102', 82, 101875.0],
 ['Andaman & Nicobar', '2023', 2, '744104', 27, 34345.0],
 ['Andaman & Nicobar', '2023', 2, '744301', 25, 41299.0],
 ['Andaman & Nicobar', '2023', 2, '744207', 22, 43459.0],
 ['Andaman & Nicobar', '2023', 2, '744112', 21, 20427.0],
 ['Andaman & Nicobar', '2023', 2, '744107', 20, 24693.0],
 ['Andaman & Nicobar', '2023', 2, '744205', 17, 31404.0],
 ['Andaman & Nicobar', '2023', 3, '744103', 191, 306744.0],
 ['Andaman & Nicobar', '2023', 3, '744105', 147, 212575.0],
 ['Andaman & Nicobar', '2023', 3, '744101', 143, 213581.0],
 ['Andaman & Nicobar', '2023', 3, '744102', 100, 120875.0],
 ['Andaman & Nicobar', '2023', 3, '744202', 35, 60750.0],
 ['Andaman & Nicobar', '2023', 3, '744104', 30, 50544.0],
 ['Andaman & Nicobar', '2023', 3, '744112', 26, 46075.0],
 ['Andaman & Nicobar', '2023', 3, '744301', 18, 34636.0],
 ['Andaman & Nicobar', '2023', 3, '744205', 16, 25131.0],
 ['Andaman & Nicobar', '2023', 3, '744302', 16, 24369.0],
 ['Andaman & Nicobar', '2023', 4, '744103', 268, 415144.0],
 ['Andaman & Nicobar', '2023', 4, '744105', 214, 372312.0],
 ['Andaman & Nicobar', '2023', 4, '744101', 181, 241849.0],
 ['Andaman & Nicobar', '2023', 4, '744102', 121, 161224.0],
 ['Andaman & Nicobar', '2023', 4, '744104', 64, 80581.0],
 ['Andaman & Nicobar', '2023', 4, '744112', 50, 50671.0],
 ['Andaman & Nicobar', '2023', 4, '744107', 42, 71047.0],
 ['Andaman & Nicobar', '2023', 4, '744202', 36, 60749.0],
 ['Andaman & Nicobar', '2023', 4, '744301', 24, 52732.0],
 ['Andaman & Nicobar', '2023', 4, '744205', 23, 38962.0],
 ['Andaman & Nicobar', '2024', 1, '744103', 302, 456306.0],
 ['Andaman & Nicobar', '2024', 1, '744105', 249, 331342.0],
 ['Andaman & Nicobar', '2024', 1, '744101', 223, 287339.0],
 ['Andaman & Nicobar', '2024', 1, '744102', 141, 182213.0],
 ['Andaman & Nicobar', '2024', 1, '744202', 59, 110482.0],
 ['Andaman & Nicobar', '2024', 1, '744104', 59, 84757.0],
 ['Andaman & Nicobar', '2024', 1, '744112', 52, 62867.0],
 ['Andaman & Nicobar', '2024', 1, '744107', 52, 73449.0],
 ['Andaman & Nicobar', '2024', 1, '744207', 40, 62007.0],
 ['Andaman & Nicobar', '2024', 1, '744205', 28, 38204.0],
 ['Andaman & Nicobar', '2024', 2, '744103', 285, 438830.0],
 ['Andaman & Nicobar', '2024', 2, '744105', 199, 276393.0],
 ['Andaman & Nicobar', '2024', 2, '744101', 157, 251503.0],
 ['Andaman & Nicobar', '2024', 2, '744102', 133, 203605.0],
 ['Andaman & Nicobar', '2024', 2, '744112', 49, 77583.0],
 ['Andaman & Nicobar', '2024', 2, '744104', 49, 91213.0],
 ['Andaman & Nicobar', '2024', 2, '744107', 34, 52311.0],
 ['Andaman & Nicobar', '2024', 2, '744202', 28, 41210.0],
 ['Andaman & Nicobar', '2024', 2, '744211', 28, 43685.0],
 ['Andaman & Nicobar', '2024', 2, '744302', 27, 37685.0],
 ['Andaman & Nicobar', '2024', 3, '744103', 359, 554559.0],
 ['Andaman & Nicobar', '2024', 3, '744102', 196, 248439.0],
 ['Andaman & Nicobar', '2024', 3, '744105', 151, 221959.0],
 ['Andaman & Nicobar', '2024', 3, '744104', 95, 128652.0],
 ['Andaman & Nicobar', '2024', 3, '744101', 92, 145811.0],
 ['Andaman & Nicobar', '2024', 3, '744106', 54, 84623.0],
 ['Andaman & Nicobar', '2024', 3, '744202', 45, 67769.0],
 ['Andaman & Nicobar', '2024', 3, '744207', 25, 27399.0],
 ['Andaman & Nicobar', '2024', 3, '744302', 24, 28210.0],
 ['Andaman & Nicobar', '2024', 3, '744301', 20, 28067.0],
 ['Andaman & Nicobar', '2024', 4, '744103', 369, 521509.0],
 ['Andaman & Nicobar', '2024', 4, '744102', 165, 228528.0],
 ['Andaman & Nicobar', '2024', 4, '744105', 161, 268432.0],
 ['Andaman & Nicobar', '2024', 4, '744104', 129, 250205.0],
 ['Andaman & Nicobar', '2024', 4, '744101', 90, 117544.0],
 ['Andaman & Nicobar', '2024', 4, '744202', 65, 107445.0],
 ['Andaman & Nicobar', '2024', 4, '744106', 53, 90277.0],
 ['Andaman & Nicobar', '2024', 4, '744301', 50, 86256.0],
 ['Andaman & Nicobar', '2024', 4, '744107', 26, 55695.0],
 ['Andaman & Nicobar', '2024', 4, '744204', 24, 45960.0],
 ['Andhra Pradesh', '2020', 2, '515001', 540, 86088.0],
 ['Andhra Pradesh', '2020', 2, '515004', 437, 71761.0],
 ['Andhra Pradesh', '2020', 2, '516360', 339, 55455.0],
 ['Andhra Pradesh', '2020', 2, '516001', 322, 50705.0],
 ['Andhra Pradesh', '2020', 2, '533005', 301, 46454.0],
 ['Andhra Pradesh', '2020', 2, '517002', 279, 43236.0],
 ['Andhra Pradesh', '2020', 2, '530016', 262, 41153.0],
 ['Andhra Pradesh', '2020', 2, '517501', 259, 43013.0],
 ['Andhra Pradesh', '2020', 2, '533103', 258, 43311.0],
 ['Andhra Pradesh', '2020', 2, '515671', 250, 43610.0],
 ['Andhra Pradesh', '2020', 3, '535003', 968, 195870.0],
 ['Andhra Pradesh', '2020', 3, '524004', 795, 165322.0],
 ['Andhra Pradesh', '2020', 3, '517501', 777, 172113.0],
 ['Andhra Pradesh', '2020', 3, '517507', 776, 201732.0],
 ['Andhra Pradesh', '2020', 3, '516001', 746, 161284.0],
 ['Andhra Pradesh', '2020', 3, '524002', 663, 143659.0],
 ['Andhra Pradesh', '2020', 3, '530016', 661, 156016.0],
 ['Andhra Pradesh', '2020', 3, '524003', 608, 128862.0],
 ['Andhra Pradesh', '2020', 3, '520010', 542, 116222.0],
 ['Andhra Pradesh', '2020', 3, '516360', 532, 135236.0],
 ['Andhra Pradesh', '2020', 4, '515001', 292, 120291.0],
 ['Andhra Pradesh', '2020', 4, '516001', 260, 110284.0],
 ['Andhra Pradesh', '2020', 4, '517501', 234, 139080.0],
 ['Andhra Pradesh', '2020', 4, '530016', 233, 101891.0],
 ['Andhra Pradesh', '2020', 4, '517507', 228, 123376.0],
 ['Andhra Pradesh', '2020', 4, '530026', 215, 132499.0],
 ['Andhra Pradesh', '2020', 4, '524002', 211, 99952.0],
 ['Andhra Pradesh', '2020', 4, '522004', 201, 102846.0],
 ['Andhra Pradesh', '2020', 4, '522001', 196, 110129.0],
 ['Andhra Pradesh', '2020', 4, '522003', 181, 79955.0],
 ['Andhra Pradesh', '2021', 1, '530016', 287, 144342.0],
 ['Andhra Pradesh', '2021', 1, '516001', 258, 130242.0],
 ['Andhra Pradesh', '2021', 1, '530026', 250, 114038.0],
 ['Andhra Pradesh', '2021', 1, '517501', 249, 105904.0],
 ['Andhra Pradesh', '2021', 1, '520010', 224, 135466.0],
 ['Andhra Pradesh', '2021', 1, '517507', 215, 169433.0],
 ['Andhra Pradesh', '2021', 1, '522001', 210, 85999.0],
 ['Andhra Pradesh', '2021', 1, '520012', 178, 127092.0],
 ['Andhra Pradesh', '2021', 1, '524002', 178, 100699.0],
 ['Andhra Pradesh', '2021', 1, '520011', 177, 70827.0],
 ['Andhra Pradesh', '2021', 2, '523002', 1409, 631953.0],
 ['Andhra Pradesh', '2021', 2, '523001', 537, 293906.0],
 ['Andhra Pradesh', '2021', 2, '517501', 374, 208258.0],
 ['Andhra Pradesh', '2021', 2, '517507', 347, 265432.0],
 ['Andhra Pradesh', '2021', 2, '530016', 323, 204624.0],
 ['Andhra Pradesh', '2021', 2, '534002', 293, 124158.0],
 ['Andhra Pradesh', '2021', 2, '534006', 284, 112884.0],
 ['Andhra Pradesh', '2021', 2, '515001', 271, 168382.0],
 ['Andhra Pradesh', '2021', 2, '516001', 268, 144765.0],
 ['Andhra Pradesh', '2021', 2, '524002', 262, 130466.0],
 ['Andhra Pradesh', '2021', 3, '520010', 299, 246736.0],
 ['Andhra Pradesh', '2021', 3, '520011', 283, 194552.0],
 ['Andhra Pradesh', '2021', 3, '517507', 282, 246665.0],
 ['Andhra Pradesh', '2021', 3, '516001', 281, 218927.0],
 ['Andhra Pradesh', '2021', 3, '517501', 281, 190890.0],
 ['Andhra Pradesh', '2021', 3, '530026', 276, 201084.0],
 ['Andhra Pradesh', '2021', 3, '520001', 252, 185104.0],
 ['Andhra Pradesh', '2021', 3, '530016', 247, 181981.0],
 ['Andhra Pradesh', '2021', 3, '520007', 234, 183730.0],
 ['Andhra Pradesh', '2021', 3, '524004', 230, 154696.0],
 ['Andhra Pradesh', '2021', 4, '524004', 568, 468698.0],
 ['Andhra Pradesh', '2021', 4, '524002', 373, 385590.0],
 ['Andhra Pradesh', '2021', 4, '517501', 372, 394057.0],
 ['Andhra Pradesh', '2021', 4, '517507', 365, 376592.0],
 ['Andhra Pradesh', '2021', 4, '516001', 301, 298417.0],
 ['Andhra Pradesh', '2021', 4, '530016', 293, 386711.0],
 ['Andhra Pradesh', '2021', 4, '520010', 254, 242094.0],
 ['Andhra Pradesh', '2021', 4, '522001', 249, 252587.0],
 ['Andhra Pradesh', '2021', 4, '530026', 238, 269565.0],
 ['Andhra Pradesh', '2021', 4, '520011', 235, 238426.0],
 ['Andhra Pradesh', '2022', 1, '523001', 501, 553651.0],
 ['Andhra Pradesh', '2022', 1, '523002', 418, 422786.0],
 ['Andhra Pradesh', '2022', 1, '524004', 365, 352581.0],
 ['Andhra Pradesh', '2022', 1, '517507', 361, 617403.0],
 ['Andhra Pradesh', '2022', 1, '517501', 352, 477461.0],
 ['Andhra Pradesh', '2022', 1, '530016', 349, 394098.0],
 ['Andhra Pradesh', '2022', 1, '516001', 346, 403725.0],
 ['Andhra Pradesh', '2022', 1, '530026', 307, 312518.0],
 ['Andhra Pradesh', '2022', 1, '520010', 297, 370767.0],
 ['Andhra Pradesh', '2022', 1, '520007', 294, 413180.0],
 ['Andhra Pradesh', '2022', 2, '520010', 394, 411471.0],
 ['Andhra Pradesh', '2022', 2, '530016', 379, 457895.0],
 ['Andhra Pradesh', '2022', 2, '517507', 376, 510705.0],
 ['Andhra Pradesh', '2022', 2, '517501', 363, 390709.0],
 ['Andhra Pradesh', '2022', 2, '520011', 359, 347013.0],
 ['Andhra Pradesh', '2022', 2, '524002', 347, 400810.0],
 ['Andhra Pradesh', '2022', 2, '516001', 344, 354936.0],
 ['Andhra Pradesh', '2022', 2, '523001', 336, 298809.0],
 ['Andhra Pradesh', '2022', 2, '523002', 318, 410402.0],
 ['Andhra Pradesh', '2022', 2, '520007', 306, 355690.0],
 ['Andhra Pradesh', '2022', 3, '524002', 485, 506293.0],
 ['Andhra Pradesh', '2022', 3, '517507', 478, 633331.0],
 ['Andhra Pradesh', '2022', 3, '517501', 477, 602653.0],
 ['Andhra Pradesh', '2022', 3, '520010', 463, 496114.0],
 ['Andhra Pradesh', '2022', 3, '520011', 444, 463855.0],
 ['Andhra Pradesh', '2022', 3, '516001', 443, 510288.0],
 ['Andhra Pradesh', '2022', 3, '530026', 421, 437652.0],
 ['Andhra Pradesh', '2022', 3, '530016', 420, 408060.0],
 ['Andhra Pradesh', '2022', 3, '520001', 411, 343460.0],
 ['Andhra Pradesh', '2022', 3, '524004', 392, 408836.0],
 ['Andhra Pradesh', '2022', 4, '517507', 596, 856272.0],
 ['Andhra Pradesh', '2022', 4, '516001', 550, 602897.0],
 ['Andhra Pradesh', '2022', 4, '517501', 543, 549451.0],
 ['Andhra Pradesh', '2022', 4, '523002', 488, 441856.0],
 ['Andhra Pradesh', '2022', 4, '530016', 457, 650737.0],
 ['Andhra Pradesh', '2022', 4, '517326', 416, 288926.0],
 ['Andhra Pradesh', '2022', 4, '524002', 416, 588408.0],
 ['Andhra Pradesh', '2022', 4, '520011', 413, 432671.0],
 ['Andhra Pradesh', '2022', 4, '522001', 407, 369435.0],
 ['Andhra Pradesh', '2022', 4, '530026', 407, 458462.0],
 ['Andhra Pradesh', '2023', 1, '517507', 468, 848915.0],
 ['Andhra Pradesh', '2023', 1, '530016', 463, 635433.0],
 ['Andhra Pradesh', '2023', 1, '517501', 456, 788976.0],
 ['Andhra Pradesh', '2023', 1, '520011', 407, 518326.0],
 ['Andhra Pradesh', '2023', 1, '516001', 396, 538812.0],
 ['Andhra Pradesh', '2023', 1, '524002', 383, 483768.0],
 ['Andhra Pradesh', '2023', 1, '520010', 377, 446022.0],
 ['Andhra Pradesh', '2023', 1, '530026', 367, 455958.0],
 ['Andhra Pradesh', '2023', 1, '520012', 353, 481246.0],
 ['Andhra Pradesh', '2023', 1, '520007', 345, 417747.0],
 ['Andhra Pradesh', '2023', 2, '517507', 616, 969092.0],
 ['Andhra Pradesh', '2023', 2, '517501', 537, 696700.0],
 ['Andhra Pradesh', '2023', 2, '520010', 472, 547680.0],
 ['Andhra Pradesh', '2023', 2, '530016', 452, 526796.0],
 ['Andhra Pradesh', '2023', 2, '520007', 433, 549179.0],
 ['Andhra Pradesh', '2023', 2, '524002', 412, 546644.0],
 ['Andhra Pradesh', '2023', 2, '520011', 405, 443320.0],
 ['Andhra Pradesh', '2023', 2, '520001', 394, 377868.0],
 ['Andhra Pradesh', '2023', 2, '524004', 371, 636260.0],
 ['Andhra Pradesh', '2023', 2, '516001', 370, 505187.0],
 ['Andhra Pradesh', '2023', 3, '517507', 681, 926705.0],
 ['Andhra Pradesh', '2023', 3, '517501', 589, 770236.0],
 ['Andhra Pradesh', '2023', 3, '530016', 577, 720125.0],
 ['Andhra Pradesh', '2023', 3, '520010', 533, 663947.0],
 ['Andhra Pradesh', '2023', 3, '520007', 527, 675611.0],
 ['Andhra Pradesh', '2023', 3, '520011', 524, 479426.0],
 ['Andhra Pradesh', '2023', 3, '530026', 520, 483441.0],
 ['Andhra Pradesh', '2023', 3, '524002', 482, 536352.0],
 ['Andhra Pradesh', '2023', 3, '524004', 431, 581425.0],
 ['Andhra Pradesh', '2023', 3, '516001', 412, 534212.0],
 ['Andhra Pradesh', '2023', 4, '530016', 563, 837356.0],
 ['Andhra Pradesh', '2023', 4, '517507', 557, 1066470.0],
 ['Andhra Pradesh', '2023', 4, '530026', 495, 565504.0],
 ['Andhra Pradesh', '2023', 4, '517501', 453, 752992.0],
 ['Andhra Pradesh', '2023', 4, '524002', 434, 553778.0],
 ['Andhra Pradesh', '2023', 4, '520011', 412, 463576.0],
 ['Andhra Pradesh', '2023', 4, '520007', 407, 516110.0],
 ['Andhra Pradesh', '2023', 4, '520010', 389, 513516.0],
 ['Andhra Pradesh', '2023', 4, '530046', 378, 607798.0],
 ['Andhra Pradesh', '2023', 4, '520001', 369, 418525.0],
 ['Andhra Pradesh', '2024', 1, '530016', 548, 763795.0],
 ['Andhra Pradesh', '2024', 1, '517507', 531, 915457.0],
 ['Andhra Pradesh', '2024', 1, '517501', 494, 749467.0],
 ['Andhra Pradesh', '2024', 1, '520010', 480, 529119.0],
 ['Andhra Pradesh', '2024', 1, '530026', 466, 524957.0],
 ['Andhra Pradesh', '2024', 1, '517326', 439, 244562.0],
 ['Andhra Pradesh', '2024', 1, '520007', 432, 691745.0],
 ['Andhra Pradesh', '2024', 1, '524002', 428, 666708.0],
 ['Andhra Pradesh', '2024', 1, '530046', 386, 614874.0],
 ['Andhra Pradesh', '2024', 1, '520011', 372, 445394.0],
 ['Andhra Pradesh', '2024', 2, '530016', 567, 878988.0],
 ['Andhra Pradesh', '2024', 2, '517507', 515, 883412.0],
 ['Andhra Pradesh', '2024', 2, '517501', 467, 775196.0],
 ['Andhra Pradesh', '2024', 2, '530014', 418, 347441.0],

In [113]:
top_insurance[['Years','Pincodes','Transaction_Count','Transaction_amount']].max()

Years                      2024
Pincodes                 854301
Transaction_Count          3947
Transaction_amount    5740577.0
dtype: object

In [114]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Top_Insurance_Table
create_query7 = '''CREATE TABLE IF NOT EXISTS top_insurance(States varchar(255), Years int, Quarter int, Pincodes float,
                                               Transaction_Count float, Transaction_amount float)'''

cur.execute(create_query7)
mydb.commit()
insert_query7 = '''INSERT INTO top_insurance(States, Years, Quarter, Pincodes,
                                               Transaction_Count, Transaction_amount)
                                               VALUES (%s, %s, %s, %s, %s, %s)'''
data7 = top_insurance.values.tolist()
cur.executemany(insert_query7, data7)
mydb.commit()

### Store_Top_transaction

In [115]:
top_transaction.columns

Index(['States', 'Years', 'Quarter', 'Pincodes', 'Transaction_Count',
       'Transaction_amount'],
      dtype='str')

In [116]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Top_Transaction_Table
create_query8 = '''CREATE TABLE IF NOT EXISTS top_transaction(States varchar(255), Years int, Quarter int, Pincodes float,
                                               Transaction_Count float, Transaction_amount float)'''

cur.execute(create_query8)
mydb.commit()
insert_query8 = '''INSERT INTO top_transaction(States, Years, Quarter, Pincodes,
                                               Transaction_Count, Transaction_amount)
                                               VALUES (%s, %s, %s, %s, %s, %s)'''
data8 = top_transaction.values.tolist()
cur.executemany(insert_query8, data8)
mydb.commit()

### Store_top_user

In [117]:
top_user.columns

Index(['States', 'Years', 'Quarter', 'Pincodes', 'RegisteredUsers'], dtype='str')

In [118]:
top_user.values.tolist()

[['Andaman & Nicobar', '2018', 1, '744103', 1608],
 ['Andaman & Nicobar', '2018', 1, '744101', 1108],
 ['Andaman & Nicobar', '2018', 1, '744105', 1075],
 ['Andaman & Nicobar', '2018', 1, '744102', 1006],
 ['Andaman & Nicobar', '2018', 1, '744104', 272],
 ['Andaman & Nicobar', '2018', 1, '744202', 237],
 ['Andaman & Nicobar', '2018', 1, '744112', 215],
 ['Andaman & Nicobar', '2018', 1, '744301', 207],
 ['Andaman & Nicobar', '2018', 1, '744107', 196],
 ['Andaman & Nicobar', '2018', 1, '744211', 156],
 ['Andaman & Nicobar', '2018', 2, '744103', 2188],
 ['Andaman & Nicobar', '2018', 2, '744101', 1521],
 ['Andaman & Nicobar', '2018', 2, '744105', 1492],
 ['Andaman & Nicobar', '2018', 2, '744102', 1419],
 ['Andaman & Nicobar', '2018', 2, '744104', 396],
 ['Andaman & Nicobar', '2018', 2, '744202', 343],
 ['Andaman & Nicobar', '2018', 2, '744112', 299],
 ['Andaman & Nicobar', '2018', 2, '744107', 293],
 ['Andaman & Nicobar', '2018', 2, '744301', 273],
 ['Andaman & Nicobar', '2018', 2, '744211', 240],
 ['Andaman & Nicobar', '2018', 3, '744103', 2741],
 ['Andaman & Nicobar', '2018', 3, '744101', 1978],
 ['Andaman & Nicobar', '2018', 3, '744105', 1935],
 ['Andaman & Nicobar', '2018', 3, '744102', 1803],
 ['Andaman & Nicobar', '2018', 3, '744104', 507],
 ['Andaman & Nicobar', '2018', 3, '744202', 446],
 ['Andaman & Nicobar', '2018', 3, '744112', 388],
 ['Andaman & Nicobar', '2018', 3, '744107', 384],
 ['Andaman & Nicobar', '2018', 3, '744301', 372],
 ['Andaman & Nicobar', '2018', 3, '744211', 327],
 ['Andaman & Nicobar', '2018', 4, '744103', 3373],
 ['Andaman & Nicobar', '2018', 4, '744101', 2498],
 ['Andaman & Nicobar', '2018', 4, '744105', 2416],
 ['Andaman & Nicobar', '2018', 4, '744102', 2231],
 ['Andaman & Nicobar', '2018', 4, '744104', 634],
 ['Andaman & Nicobar', '2018', 4, '744202', 554],
 ['Andaman & Nicobar', '2018', 4, '744107', 548],
 ['Andaman & Nicobar', '2018', 4, '744112', 496],
 ['Andaman & Nicobar', '2018', 4, '744211', 433],
 ['Andaman & Nicobar', '2018', 4, '744301', 425],
 ['Andaman & Nicobar', '2019', 1, '744103', 4136],
 ['Andaman & Nicobar', '2019', 1, '744101', 3030],
 ['Andaman & Nicobar', '2019', 1, '744105', 2994],
 ['Andaman & Nicobar', '2019', 1, '744102', 2667],
 ['Andaman & Nicobar', '2019', 1, '744104', 756],
 ['Andaman & Nicobar', '2019', 1, '744202', 753],
 ['Andaman & Nicobar', '2019', 1, '744107', 667],
 ['Andaman & Nicobar', '2019', 1, '744112', 585],
 ['Andaman & Nicobar', '2019', 1, '744211', 524],
 ['Andaman & Nicobar', '2019', 1, '744301', 488],
 ['Andaman & Nicobar', '2019', 2, '744103', 4748],
 ['Andaman & Nicobar', '2019', 2, '744101', 3631],
 ['Andaman & Nicobar', '2019', 2, '744105', 3547],
 ['Andaman & Nicobar', '2019', 2, '744102', 3008],
 ['Andaman & Nicobar', '2019', 2, '744202', 885],
 ['Andaman & Nicobar', '2019', 2, '744104', 878],
 ['Andaman & Nicobar', '2019', 2, '744107', 787],
 ['Andaman & Nicobar', '2019', 2, '744112', 672],
 ['Andaman & Nicobar', '2019', 2, '744211', 633],
 ['Andaman & Nicobar', '2019', 2, '744301', 534],
 ['Andaman & Nicobar', '2019', 3, '744103', 5218],
 ['Andaman & Nicobar', '2019', 3, '744101', 4026],
 ['Andaman & Nicobar', '2019', 3, '744105', 3920],
 ['Andaman & Nicobar', '2019', 3, '744102', 3250],
 ['Andaman & Nicobar', '2019', 3, '744202', 982],
 ['Andaman & Nicobar', '2019', 3, '744104', 975],
 ['Andaman & Nicobar', '2019', 3, '744107', 885],
 ['Andaman & Nicobar', '2019', 3, '744112', 765],
 ['Andaman & Nicobar', '2019', 3, '744211', 701],
 ['Andaman & Nicobar', '2019', 3, '744301', 575],
 ['Andaman & Nicobar', '2019', 4, '744103', 5637],
 ['Andaman & Nicobar', '2019', 4, '744101', 4321],
 ['Andaman & Nicobar', '2019', 4, '744105', 4277],
 ['Andaman & Nicobar', '2019', 4, '744102', 3485],
 ['Andaman & Nicobar', '2019', 4, '744202', 1087],
 ['Andaman & Nicobar', '2019', 4, '744104', 1062],
 ['Andaman & Nicobar', '2019', 4, '744107', 953],
 ['Andaman & Nicobar', '2019', 4, '744112', 812],
 ['Andaman & Nicobar', '2019', 4, '744211', 783],
 ['Andaman & Nicobar', '2019', 4, '744301', 611],
 ['Andaman & Nicobar', '2020', 1, '744103', 6108],
 ['Andaman & Nicobar', '2020', 1, '744101', 4689],
 ['Andaman & Nicobar', '2020', 1, '744105', 4684],
 ['Andaman & Nicobar', '2020', 1, '744102', 3727],
 ['Andaman & Nicobar', '2020', 1, '744202', 1216],
 ['Andaman & Nicobar', '2020', 1, '744104', 1154],
 ['Andaman & Nicobar', '2020', 1, '744107', 1062],
 ['Andaman & Nicobar', '2020', 1, '744112', 889],
 ['Andaman & Nicobar', '2020', 1, '744211', 886],
 ['Andaman & Nicobar', '2020', 1, '744301', 669],
 ['Andaman & Nicobar', '2020', 2, '744103', 6804],
 ['Andaman & Nicobar', '2020', 2, '744105', 5479],
 ['Andaman & Nicobar', '2020', 2, '744101', 5365],
 ['Andaman & Nicobar', '2020', 2, '744102', 4066],
 ['Andaman & Nicobar', '2020', 2, '744202', 1475],
 ['Andaman & Nicobar', '2020', 2, '744104', 1333],
 ['Andaman & Nicobar', '2020', 2, '744107', 1252],
 ['Andaman & Nicobar', '2020', 2, '744112', 1039],
 ['Andaman & Nicobar', '2020', 2, '744211', 1036],
 ['Andaman & Nicobar', '2020', 2, '744205', 806],
 ['Andaman & Nicobar', '2020', 3, '744103', 8318],
 ['Andaman & Nicobar', '2020', 3, '744105', 7007],
 ['Andaman & Nicobar', '2020', 3, '744101', 6881],
 ['Andaman & Nicobar', '2020', 3, '744102', 4919],
 ['Andaman & Nicobar', '2020', 3, '744202', 1965],
 ['Andaman & Nicobar', '2020', 3, '744104', 1718],
 ['Andaman & Nicobar', '2020', 3, '744107', 1710],
 ['Andaman & Nicobar', '2020', 3, '744112', 1372],
 ['Andaman & Nicobar', '2020', 3, '744211', 1279],
 ['Andaman & Nicobar', '2020', 3, '744205', 1008],
 ['Andaman & Nicobar', '2020', 4, '744103', 10408],
 ['Andaman & Nicobar', '2020', 4, '744105', 8962],
 ['Andaman & Nicobar', '2020', 4, '744101', 8593],
 ['Andaman & Nicobar', '2020', 4, '744102', 5882],
 ['Andaman & Nicobar', '2020', 4, '744202', 2711],
 ['Andaman & Nicobar', '2020', 4, '744107', 2346],
 ['Andaman & Nicobar', '2020', 4, '744104', 2167],
 ['Andaman & Nicobar', '2020', 4, '744112', 1761],
 ['Andaman & Nicobar', '2020', 4, '744211', 1579],
 ['Andaman & Nicobar', '2020', 4, '744205', 1346],
 ['Andaman & Nicobar', '2021', 1, '744103', 11416],
 ['Andaman & Nicobar', '2021', 1, '744105', 9934],
 ['Andaman & Nicobar', '2021', 1, '744101', 9457],
 ['Andaman & Nicobar', '2021', 1, '744102', 6395],
 ['Andaman & Nicobar', '2021', 1, '744202', 3005],
 ['Andaman & Nicobar', '2021', 1, '744107', 2586],
 ['Andaman & Nicobar', '2021', 1, '744104', 2383],
 ['Andaman & Nicobar', '2021', 1, '744112', 1940],
 ['Andaman & Nicobar', '2021', 1, '744211', 1774],
 ['Andaman & Nicobar', '2021', 1, '744205', 1505],
 ['Andaman & Nicobar', '2021', 2, '744103', 12268],
 ['Andaman & Nicobar', '2021', 2, '744105', 10668],
 ['Andaman & Nicobar', '2021', 2, '744101', 10120],
 ['Andaman & Nicobar', '2021', 2, '744102', 6837],
 ['Andaman & Nicobar', '2021', 2, '744202', 3261],
 ['Andaman & Nicobar', '2021', 2, '744107', 2783],
 ['Andaman & Nicobar', '2021', 2, '744104', 2573],
 ['Andaman & Nicobar', '2021', 2, '744112', 2083],
 ['Andaman & Nicobar', '2021', 2, '744211', 1904],
 ['Andaman & Nicobar', '2021', 2, '744205', 1626],
 ['Andaman & Nicobar', '2021', 3, '744103', 13198],
 ['Andaman & Nicobar', '2021', 3, '744105', 11480],
 ['Andaman & Nicobar', '2021', 3, '744101', 10866],
 ['Andaman & Nicobar', '2021', 3, '744102', 7313],
 ['Andaman & Nicobar', '2021', 3, '744202', 3543],
 ['Andaman & Nicobar', '2021', 3, '744107', 3027],
 ['Andaman & Nicobar', '2021', 3, '744104', 2777],
 ['Andaman & Nicobar', '2021', 3, '744112', 2250],
 ['Andaman & Nicobar', '2021', 3, '744211', 2055],
 ['Andaman & Nicobar', '2021', 3, '744205', 1771],
 ['Andaman & Nicobar', '2021', 4, '744103', 14127],
 ['Andaman & Nicobar', '2021', 4, '744105', 12300],
 ['Andaman & Nicobar', '2021', 4, '744101', 11623],
 ['Andaman & Nicobar', '2021', 4, '744102', 7813],
 ['Andaman & Nicobar', '2021', 4, '744202', 3815],
 ['Andaman & Nicobar', '2021', 4, '744107', 3247],
 ['Andaman & Nicobar', '2021', 4, '744104', 2962],
 ['Andaman & Nicobar', '2021', 4, '744112', 2411],
 ['Andaman & Nicobar', '2021', 4, '744211', 2200],
 ['Andaman & Nicobar', '2021', 4, '744205', 1902],
 ['Andaman & Nicobar', '2022', 1, '744103', 15011],
 ['Andaman & Nicobar', '2022', 1, '744105', 13070],
 ['Andaman & Nicobar', '2022', 1, '744101', 12300],
 ['Andaman & Nicobar', '2022', 1, '744102', 8271],
 ['Andaman & Nicobar', '2022', 1, '744202', 4107],
 ['Andaman & Nicobar', '2022', 1, '744107', 3455],
 ['Andaman & Nicobar', '2022', 1, '744104', 3146],
 ['Andaman & Nicobar', '2022', 1, '744112', 2552],
 ['Andaman & Nicobar', '2022', 1, '744211', 2344],
 ['Andaman & Nicobar', '2022', 1, '744205', 2034],
 ['Andaman & Nicobar', '2022', 2, '744103', 15799],
 ['Andaman & Nicobar', '2022', 2, '744105', 13791],
 ['Andaman & Nicobar', '2022', 2, '744101', 12947],
 ['Andaman & Nicobar', '2022', 2, '744102', 8709],
 ['Andaman & Nicobar', '2022', 2, '744202', 4361],
 ['Andaman & Nicobar', '2022', 2, '744107', 3674],
 ['Andaman & Nicobar', '2022', 2, '744104', 3319],
 ['Andaman & Nicobar', '2022', 2, '744112', 2700],
 ['Andaman & Nicobar', '2022', 2, '744211', 2471],
 ['Andaman & Nicobar', '2022', 2, '744205', 2162],
 ['Andaman & Nicobar', '2022', 3, '744103', 16666],
 ['Andaman & Nicobar', '2022', 3, '744105', 14503],
 ['Andaman & Nicobar', '2022', 3, '744101', 13649],
 ['Andaman & Nicobar', '2022', 3, '744102', 9148],
 ['Andaman & Nicobar', '2022', 3, '744202', 4572],
 ['Andaman & Nicobar', '2022', 3, '744107', 3868],
 ['Andaman & Nicobar', '2022', 3, '744104', 3493],
 ['Andaman & Nicobar', '2022', 3, '744112', 2837],
 ['Andaman & Nicobar', '2022', 3, '744211', 2577],
 ['Andaman & Nicobar', '2022', 3, '744205', 2268],
 ['Andaman & Nicobar', '2022', 4, '744103', 17406],
 ['Andaman & Nicobar', '2022', 4, '744105', 15185],
 ['Andaman & Nicobar', '2022', 4, '744101', 14337],
 ['Andaman & Nicobar', '2022', 4, '744102', 9591],
 ['Andaman & Nicobar', '2022', 4, '744202', 4760],
 ['Andaman & Nicobar', '2022', 4, '744107', 4051],
 ['Andaman & Nicobar', '2022', 4, '744104', 3647],
 ['Andaman & Nicobar', '2022', 4, '744112', 2975],
 ['Andaman & Nicobar', '2022', 4, '744211', 2679],
 ['Andaman & Nicobar', '2022', 4, '744205', 2358],
 ['Andaman & Nicobar', '2023', 1, '744103', 18209],
 ['Andaman & Nicobar', '2023', 1, '744105', 15848],
 ['Andaman & Nicobar', '2023', 1, '744101', 15006],
 ['Andaman & Nicobar', '2023', 1, '744102', 10033],
 ['Andaman & Nicobar', '2023', 1, '744202', 4993],
 ['Andaman & Nicobar', '2023', 1, '744107', 4239],
 ['Andaman & Nicobar', '2023', 1, '744104', 3795],
 ['Andaman & Nicobar', '2023', 1, '744112', 3141],
 ['Andaman & Nicobar', '2023', 1, '744211', 2792],
 ['Andaman & Nicobar', '2023', 1, '744205', 2480],
 ['Andaman & Nicobar', '2023', 2, '744103', 18944],
 ['Andaman & Nicobar', '2023', 2, '744105', 16488],
 ['Andaman & Nicobar', '2023', 2, '744101', 15562],
 ['Andaman & Nicobar', '2023', 2, '744102', 10387],
 ['Andaman & Nicobar', '2023', 2, '744202', 5239],
 ['Andaman & Nicobar', '2023', 2, '744107', 4425],
 ['Andaman & Nicobar', '2023', 2, '744104', 3937],
 ['Andaman & Nicobar', '2023', 2, '744112', 3261],
 ['Andaman & Nicobar', '2023', 2, '744211', 2917],
 ['Andaman & Nicobar', '2023', 2, '744205', 2605],
 ['Andaman & Nicobar', '2023', 3, '744103', 19673],
 ['Andaman & Nicobar', '2023', 3, '744105', 17171],
 ['Andaman & Nicobar', '2023', 3, '744101', 16188],
 ['Andaman & Nicobar', '2023', 3, '744102', 10799],
 ['Andaman & Nicobar', '2023', 3, '744202', 5480],
 ['Andaman & Nicobar', '2023', 3, '744107', 4591],
 ['Andaman & Nicobar', '2023', 3, '744104', 4082],
 ['Andaman & Nicobar', '2023', 3, '744112', 3382],
 ['Andaman & Nicobar', '2023', 3, '744211', 3033],
 ['Andaman & Nicobar', '2023', 3, '744205', 2716],
 ['Andaman & Nicobar', '2023', 4, '744103', 20431],
 ['Andaman & Nicobar', '2023', 4, '744105', 17824],
 ['Andaman & Nicobar', '2023', 4, '744101', 16772],
 ['Andaman & Nicobar', '2023', 4, '744102', 11155],
 ['Andaman & Nicobar', '2023', 4, '744202', 5700],
 ['Andaman & Nicobar', '2023', 4, '744107', 4759],
 ['Andaman & Nicobar', '2023', 4, '744104', 4224],
 ['Andaman & Nicobar', '2023', 4, '744112', 3496],
 ['Andaman & Nicobar', '2023', 4, '744211', 3141],
 ['Andaman & Nicobar', '2023', 4, '744205', 2822],
 ['Andaman & Nicobar', '2024', 1, '744103', 21242],
 ['Andaman & Nicobar', '2024', 1, '744105', 18563],
 ['Andaman & Nicobar', '2024', 1, '744101', 17431],
 ['Andaman & Nicobar', '2024', 1, '744102', 11589],
 ['Andaman & Nicobar', '2024', 1, '744202', 5978],
 ['Andaman & Nicobar', '2024', 1, '744107', 5006],
 ['Andaman & Nicobar', '2024', 1, '744104', 4398],
 ['Andaman & Nicobar', '2024', 1, '744112', 3629],
 ['Andaman & Nicobar', '2024', 1, '744211', 3292],
 ['Andaman & Nicobar', '2024', 1, '744205', 2975],
 ['Andaman & Nicobar', '2024', 2, '744103', 22049],
 ['Andaman & Nicobar', '2024', 2, '744105', 19314],
 ['Andaman & Nicobar', '2024', 2, '744101', 18110],
 ['Andaman & Nicobar', '2024', 2, '744102', 12053],
 ['Andaman & Nicobar', '2024', 2, '744202', 6212],
 ['Andaman & Nicobar', '2024', 2, '744107', 5184],
 ['Andaman & Nicobar', '2024', 2, '744104', 4570],
 ['Andaman & Nicobar', '2024', 2, '744112', 3761],
 ['Andaman & Nicobar', '2024', 2, '744211', 3409],
 ['Andaman & Nicobar', '2024', 2, '744205', 3090],
 ['Andaman & Nicobar', '2024', 3, '744103', 42228],
 ['Andaman & Nicobar', '2024', 3, '744105', 22090],
 ['Andaman & Nicobar', '2024', 3, '744102', 17618],
 ['Andaman & Nicobar', '2024', 3, '744104', 17606],
 ['Andaman & Nicobar', '2024', 3, '744101', 11136],
 ['Andaman & Nicobar', '2024', 3, '744202', 9206],
 ['Andaman & Nicobar', '2024', 3, '744106', 7682],
 ['Andaman & Nicobar', '2024', 3, '744211', 7045],
 ['Andaman & Nicobar', '2024', 3, '744107', 6127],
 ['Andaman & Nicobar', '2024', 3, '744301', 4126],
 ['Andaman & Nicobar', '2024', 4, '744103', 43485],
 ['Andaman & Nicobar', '2024', 4, '744105', 22976],
 ['Andaman & Nicobar', '2024', 4, '744104', 18509],
 ['Andaman & Nicobar', '2024', 4, '744102', 18169],
 ['Andaman & Nicobar', '2024', 4, '744101', 11564],
 ['Andaman & Nicobar', '2024', 4, '744202', 9545],
 ['Andaman & Nicobar', '2024', 4, '744106', 7974],
 ['Andaman & Nicobar', '2024', 4, '744211', 7337],
 ['Andaman & Nicobar', '2024', 4, '744107', 6333],
 ['Andaman & Nicobar', '2024', 4, '744301', 4221],
 ['Andhra Pradesh', '2018', 1, '517501', 39884],
 ['Andhra Pradesh', '2018', 1, '530016', 34201],
 ['Andhra Pradesh', '2018', 1, '517507', 34111],
 ['Andhra Pradesh', '2018', 1, '515001', 31964],
 ['Andhra Pradesh', '2018', 1, '516001', 29078],
 ['Andhra Pradesh', '2018', 1, '518002', 29043],
 ['Andhra Pradesh', '2018', 1, '530026', 26889],
 ['Andhra Pradesh', '2018', 1, '516360', 26187],
 ['Andhra Pradesh', '2018', 1, '520010', 24397],
 ['Andhra Pradesh', '2018', 1, '524002', 23439],
 ['Andhra Pradesh', '2018', 2, '517501', 53468],
 ['Andhra Pradesh', '2018', 2, '517507', 45241],
 ['Andhra Pradesh', '2018', 2, '530016', 43386],
 ['Andhra Pradesh', '2018', 2, '515001', 42466],
 ['Andhra Pradesh', '2018', 2, '516001', 38402],
 ['Andhra Pradesh', '2018', 2, '518002', 37593],
 ['Andhra Pradesh', '2018', 2, '516360', 34544],
 ['Andhra Pradesh', '2018', 2, '530026', 34126],
 ['Andhra Pradesh', '2018', 2, '520010', 31871],
 ['Andhra Pradesh', '2018', 2, '524002', 31134],
 ['Andhra Pradesh', '2018', 3, '517501', 65157],
 ['Andhra Pradesh', '2018', 3, '517507', 54849],
 ['Andhra Pradesh', '2018', 3, '530016', 52259],
 ['Andhra Pradesh', '2018', 3, '515001', 51449],
 ['Andhra Pradesh', '2018', 3, '516001', 46691],
 ['Andhra Pradesh', '2018', 3, '518002', 45145],
 ['Andhra Pradesh', '2018', 3, '516360', 41963],
 ['Andhra Pradesh', '2018', 3, '530026', 40580],
 ['Andhra Pradesh', '2018', 3, '520010', 38918],
 ['Andhra Pradesh', '2018', 3, '524002', 37559],
 ['Andhra Pradesh', '2018', 4, '517501', 82873],
 ['Andhra Pradesh', '2018', 4, '517507', 70421],
 ['Andhra Pradesh', '2018', 4, '530016', 65549],
 ['Andhra Pradesh', '2018', 4, '515001', 63576],
 ['Andhra Pradesh', '2018', 4, '516001', 58028],
 ['Andhra Pradesh', '2018', 4, '518002', 55735],
 ['Andhra Pradesh', '2018', 4, '516360', 52058],
 ['Andhra Pradesh', '2018', 4, '530026', 51900],
 ['Andhra Pradesh', '2018', 4, '520010', 48991],
 ['Andhra Pradesh', '2018', 4, '524002', 46616],
 ['Andhra Pradesh', '2019', 1, '517501', 100561],
 ['Andhra Pradesh', '2019', 1, '517507', 85980],
 ['Andhra Pradesh', '2019', 1, '530016', 77790],
 ['Andhra Pradesh', '2019', 1, '515001', 75171],
 ['Andhra Pradesh', '2019', 1, '516001', 68514],
 ['Andhra Pradesh', '2019', 1, '518002', 66689],
 ['Andhra Pradesh', '2019', 1, '530026', 61623],
 ['Andhra Pradesh', '2019', 1, '516360', 60798],
 ['Andhra Pradesh', '2019', 1, '520010', 59055],
 ['Andhra Pradesh', '2019', 1, '524002', 55931],
 ['Andhra Pradesh', '2019', 2, '517501', 113033],
 ['Andhra Pradesh', '2019', 2, '517507', 97534],
 ['Andhra Pradesh', '2019', 2, '530016', 87556],
 ['Andhra Pradesh', '2019', 2, '515001', 84157],
 ['Andhra Pradesh', '2019', 2, '516001', 76617],
 ['Andhra Pradesh', '2019', 2, '518002', 75952],
 ['Andhra Pradesh', '2019', 2, '530026', 68283],
 ['Andhra Pradesh', '2019', 2, '516360', 66885],
 ['Andhra Pradesh', '2019', 2, '520010', 66082],
 ['Andhra Pradesh', '2019', 2, '524002', 62933],
 ['Andhra Pradesh', '2019', 3, '517501', 124727],
 ['Andhra Pradesh', '2019', 3, '517507', 108199],
 ['Andhra Pradesh', '2019', 3, '530016', 97323],
 ['Andhra Pradesh', '2019', 3, '515001', 93191],
 ['Andhra Pradesh', '2019', 3, '518002', 84918],
 ['Andhra Pradesh', '2019', 3, '516001', 84693],
 ['Andhra Pradesh', '2019', 3, '530026', 74501],
 ['Andhra Pradesh', '2019', 3, '516360', 73267],
 ['Andhra Pradesh', '2019', 3, '520010', 72722],
 ['Andhra Pradesh', '2019', 3, '524002', 69783],
 ['Andhra Pradesh', '2019', 4, '517501', 136436],
 ['Andhra Pradesh', '2019', 4, '517507', 119146],
 ['Andhra Pradesh', '2019', 4, '530016', 106404],
 ['Andhra Pradesh', '2019', 4, '515001', 102848],
 ['Andhra Pradesh', '2019', 4, '516001', 94209],
 ['Andhra Pradesh', '2019', 4, '518002', 94193],
 ['Andhra Pradesh', '2019', 4, '516360', 81619],
 ['Andhra Pradesh', '2019', 4, '530026', 81191],
 ['Andhra Pradesh', '2019', 4, '520010', 79453],
 ['Andhra Pradesh', '2019', 4, '524002', 77681],
 ['Andhra Pradesh', '2020', 1, '517501', 146823],
 ['Andhra Pradesh', '2020', 1, '517507', 129214],
 ['Andhra Pradesh', '2020', 1, '530016', 114042],
 ['Andhra Pradesh', '2020', 1, '515001', 111359],
 ['Andhra Pradesh', '2020', 1, '518002', 102905],
 ['Andhra Pradesh', '2020', 1, '516001', 102893],
 ['Andhra Pradesh', '2020', 1, '516360', 89774],
 ['Andhra Pradesh', '2020', 1, '530026', 87449],
 ['Andhra Pradesh', '2020', 1, '524002', 85878],
 ['Andhra Pradesh', '2020', 1, '520010', 85779],
 ['Andhra Pradesh', '2020', 2, '517501', 156221],
 ['Andhra Pradesh', '2020', 2, '517507', 138735],
 ['Andhra Pradesh', '2020', 2, '530016', 120621],
 ['Andhra Pradesh', '2020', 2, '515001', 119223],
 ['Andhra Pradesh', '2020', 2, '518002', 112673],
 ['Andhra Pradesh', '2020', 2, '516001', 111898],
 ['Andhra Pradesh', '2020', 2, '516360', 98803],
 ['Andhra Pradesh', '2020', 2, '524002', 93834],
 ['Andhra Pradesh', '2020', 2, '530026', 93224],
 ['Andhra Pradesh', '2020', 2, '520010', 91299],
 ['Andhra Pradesh', '2020', 3, '517501', 166768],
 ['Andhra Pradesh', '2020', 3, '517507', 149001],
 ['Andhra Pradesh', '2020', 3, '515001', 128227],
 ['Andhra Pradesh', '2020', 3, '530016', 128059],
 ['Andhra Pradesh', '2020', 3, '518002', 121529],
 ['Andhra Pradesh', '2020', 3, '516001', 120997],
 ['Andhra Pradesh', '2020', 3, '516360', 108073],
 ['Andhra Pradesh', '2020', 3, '524002', 102103],
 ['Andhra Pradesh', '2020', 3, '530026', 99754],
 ['Andhra Pradesh', '2020', 3, '520010', 97752],
 ['Andhra Pradesh', '2020', 4, '517501', 178328],
 ['Andhra Pradesh', '2020', 4, '517507', 160062],
 ['Andhra Pradesh', '2020', 4, '515001', 137945],
 ['Andhra Pradesh', '2020', 4, '530016', 136049],
 ['Andhra Pradesh', '2020', 4, '518002', 130871],

In [119]:
mydb = psycopg2.connect(host= "localhost",port= 5432,database = "phonepe_pulse_data",user= "postgres",password = "Post!2025")
cur=mydb.cursor()
#Top_User_Table
create_query9 = '''CREATE TABLE IF NOT EXISTS top_user(States varchar(255), Years int, Quarter int, Pincodes float,
                                               RegisteredUsers float)'''

cur.execute(create_query9)
mydb.commit()
insert_query9 = '''INSERT INTO top_user(States, Years, Quarter, Pincodes,
                                               RegisteredUsers)
                                               VALUES (%s, %s, %s, %s, %s)'''
data9 = top_user.values.tolist()
cur.executemany(insert_query9, data9)
mydb.commit()